### ISSUE TITLE
NOOBS v1.3b initialisation box doesn't disappear after failure to download distribution list

### ISSUE THREAD

**Issue by rungeekrun** [raspberrypi/noobs#101]
When booting up NOOBS v1.3b and attached to a network without direct internet access (ie. network proxy), the "Please wait while NOOBS initialises" dialog box doesn't disappear.

The dialog box "Error downloading distribution list from internet" appears, and when you close it, the dialog box mentioned above should, in my mind, terminate, but it doesn't. You can move it out of the way, and continue to install a local image.

If the network cable is not attached at boot, the "Please wait while NOOBS initialises" dialog box displays, then disappears after a few seconds, as it should.

**Comment by Ruffio** [comment]
@lurch is this still an issue?

**Comment by XECDesign** [comment]
Inactive
