### ISSUE TITLE
Blank/Black screen after boot from NOOBS

### ISSUE THREAD

**Issue by jpswade** [raspberrypi/noobs#117]
I've installed NOOBS v1.3 on another SD card.

  I've installed OpenELEC and Rasbian.

  OpenELEC will boot with no problems.

  Rasbian does not, it simply shows a blank/black screen.

**Comment by lupa18** [comment]
Here the same than @OnkelTem 
This NOOBS not working and I lose lot of time :(

**Comment by lurch** [comment]
@lupa18 You're commenting on an issue which was closed 3 years ago - there's been many changes to NOOBS since then.
If you're having problems, please open a new issue, providing as much information as you can.
