### ISSUE TITLE
Issues with 16G PNY CLass 10 SDHC card

### ISSUE THREAD

**Issue by rdoerr01** [raspberrypi/noobs#118]
When trying to install NOOBS v1.3 with the Local and Network file, it boots up fine and sits for a very long time at the step "Formatting settings partition".  If you wait about 3 minutes it will finally get past that and have some other error message and then it comes up but doesn't show any OS's in the Dialog Box.

**Comment by Ruffio** [comment]
@lurch is this still in progress?

**Comment by lurch** [comment]
Can any of the previous commenters in this thread try re-testing with NOOBS v1.4 or above?
If not I may have to close this issue due to lack of activity...

**Comment by NicoHood** [comment]
This SD card bug is still there, this issue is duplicated somewhere. But I think its gone for Pi1 while it reappeared with the pi2 and is still there.

**Comment by lurch** [comment]
@NicoHood The Pi2 SD-card bug is #230, which AUIU is an entirely separate bug from the one being discussed here. But with so many different SD-card related bugs (see also #265, #258, #174) it's difficult to separate them into different categories (especially when they're so difficult to try and reproduce!).

**Comment by XECDesign** [comment]
Closing since OP hasn't responded since 2014 and there have been several SD card issue fixes added since then.
