### ISSUE TITLE
Error resizing FAT partition

### ISSUE THREAD

**Issue by itskdog** [raspberrypi/noobs#121]
When I start NOOBS 1.3 (this happens every time) I get the following error when it tries resizing the FAT Partition of my SanDisk Ultra 8GB Class 10 SDHC card.

> Error resizing existing FAT partition
> WARNING: you are attempting to use /usr/sbin/parted to operate on (resize) a file system.
> /usr/sbin/parted's file system manipulation code is not as robust  as what you'll find in
> dedicated, file-system-specific packages like e2fsprogs. We reccomend you use /usr/sbin/parted only to manipulate partition tables, whenever possible.
> Support for performing most operations on most types of file systems will be removed in an upcoming release
> Error: Unable to satisfy all constraints on the partition

How do I do this? Is it possible to manually resize it (and then complete the setup) on a machine other than the Pi (e.g. Wubi or a Linux VM)?

**Comment by adamshamsudeen** [comment]
Try formatting your SD card from your mobile phone or Camera.

**Comment by enapupe** [comment]
I know this is old but i cannot use the card that was formatted by my android phone.. I formatted it via phone options and used https://play.google.com/store/apps/details?id=com.redrobe.raspicardimager&hl=en app. 
Now I'm looking for a way to fix this using just the recovery mode, because i don't have a card reader on me.. I'm using just the phone.

**Comment by lurch** [comment]
@enapupe How big is your SD card? If it's 64GB or more then see https://www.raspberrypi.org/documentation/installation/sdxc_formatting.md - AFAIK this needs to be done on a computer and can't be done via a phone or camera.

**Comment by enapupe** [comment]
It was a 8gb microsd card. I do have a computer, I'm just lazy - the wrong way, because i spend about 3 hours trying to do this with just the phone/pi and recovery mode 😅. After a few formats and tryouts I gave up.

**Comment by Everton1234** [comment]
> When I start NOOBS 1.3 (this happens every time) I get the following error when it tries resizing the FAT Partition of my SanDisk Ultra 8GB Class 10 SDHC card.
> 
> > Error resizing existing FAT partition
> > WARNING: you are attempting to use /usr/sbin/parted to operate on (resize) a file system.
> > /usr/sbin/parted's file system manipulation code is not as robust  as what you'll find in
> > dedicated, file-system-specific packages like e2fsprogs. We reccomend you use /usr/sbin/parted only to manipulate partition tables, whenever possible.
> > Support for performing most operations on most types of file systems will be removed in an upcoming release
> > Error: Unable to satisfy all constraints on the partition
> 
> How do I do this? Is it possible to manually resize it (and then complete the setup) on a machine other than the Pi (e.g. Wubi or a Linux VM)?

Your post has just solved my problem. I was having the same issue two days into owning a Pii and your solution has been essential to my progression.

**Comment by Daripa** [comment]
Had a similar Error, failed to resize, asked if i have a gpt disk. used this method to fix it https://unix.stackexchange.com/questions/202749/remove-all-traces-of-gpt-disk-label

**Comment by MarcWH7750** [comment]
I just ran into this. I had used the SD Formatter 5.0 on two cards (8g & 32gb) same on both.  I ended up just putting the card back into the cardreader on my PC and Windows said there was a problem with it and offered to scan it.  I let the scan run and that resolved the issue.
