### ISSUE TITLE
Menu navigation with TV remote (hdmi cec)

### ISSUE THREAD

**Issue by LodewijkSioen** [raspberrypi/noobs#128]
I'm using NOOBS as my multiboot system in my Rasberry. I have two OSses: OpenElec to use my pi as a media center and Raspian for toying around in Linux. I also have a bluetooth keyboard that I have paired in Raspian. Obiously, I cannot use this keyboard in the OS selection menu.

What I would love to do, is to use my TV remote control to select the OS I want to boot in. This is possible by using [HDMI CEC](http://en.wikipedia.org/wiki/HDMI#CEC). I can already use CEC to navigate in OpenElec, so there are [compatible libraries out there](http://elinux.org/CEC_%28Consumer_Electronics_Control%29_over_HDMI).

Is implementing CEC control possible in NOOBS?

**Comment by atwright147** [comment]
Sorry to raise this issue from the ashes but couldn't libcec be setup as a compile option or couldn'y you offer two versions, one with and one without CEC?

**Comment by calvarezn** [comment]
+1
The main reason why I use berryboot instead of noobs it's because of its CEC support.

**Comment by Haris1977** [comment]
The problem in berryboot though is that you can not upgrade openelec ...:(

**Comment by Ruffio** [comment]
@LodewijkSioen is this still an issue?

**Comment by LodewijkSioen** [comment]
Well, there is no CEC control in NOOBS, so this is still an 'issue' (more a feature request than an issue).

However, if you have no plans to implement this, you can close this.

**Comment by Sabcoll** [comment]
+1

Is there any way to edit noobs manually? I would like to add CEC support, even though its not implemented from scratch...

**Comment by druidamix** [comment]
Raspberry is used a lot on televisions.
Have to use a mouse....
For me CEC Is essential.

is frustrating.
Noobs doesn't have cec
and berryboot can't update distros.

Alternative two sd's....

**Comment by Anubi85** [comment]
+1

I use NOOBS for a multiboot system (OSMC, RetroPie, Raspbian)
When I  boot in OSMC or RetroPie I don't need a keyboard, so I think CEC is a good features to add to NOOBS :)

**Comment by draxx31** [comment]
Hello everybody,

For me it is mandatory to have hdmi-ceci enabled in noobs. A lot of person use noobs to manage their different installation and in many case, they use their raspberry pi in the living room on the main TV with a media center (openelec for example).

It is not very useful to use each time a keyboard instead to use an all in one TV remote....

**Comment by procount** [comment]
Hi @maxnet - I'm having a go at adding CEC support like you suggested. All compiles well, but I'm missing some dependencies. How do I ensure the following shared libraries get included and are referenced with the right symlinks etc.?
libbcm_host.so
libdl.so.2
librt.so.1
libc.so.6
Some of these libraries seem to be included already, but not the correct versions.

**Comment by procount** [comment]
I have no idea what I'm doing here, but I added LIBS+= -lrt -ldl to recovery.pro and that got libdl.so built.
Then I added some symlinks to resolve the others to what seemed likely targets:

ln -fs "librt-0.9.33.2.so" "$BUILDROOT_TARGET_DIR/lib/librt.so.1"
ln -fs "libuClibc-0.9.33.2.so" "$BUILDROOT_TARGET_DIR/lib/libc.so.6"
ln -fs "ld-uClibc-0.9.33.2.so" "$BUILDROOT_TARGET_DIR/lib/ld-linux-armhf.so.3"

So now my libs link, but it looks like some are wrong because there are now some unresolved symbols:
_rtld_global_ro
_libc_intl_domainname
_rtld_global

**Comment by lurch** [comment]
The only thing I can suggest is reading through the buildroot [documentation](https://buildroot.org/docs.html) :-/

**Comment by procount** [comment]
OK, so I think I have resolved all libs and symbols now. I just have to work out why the TV is not detecting it.....

**Comment by seppforcher** [comment]
@procount Any success so far? Maybe any guidance to build it myself?
I'm really interested in a CEC enables NOOBs

**Comment by procount** [comment]
I'm having a little break from CEC doing some other stuff, but hope to get back to it soon. If I make any further progress I'll post news here.

**Comment by procount** [comment]
I had a few minutes spare, so I had another go at this - and it now works!, Well, at least I can move the cursor up and down. I need to see what keys are actually mapped on my remote, but it's looking very promising. :)

**Comment by seppforcher** [comment]
That is indeed great news! 
Now hopefully this will make it into the next noobs release.

**Comment by seppforcher** [comment]
@procount May I ask you to share your results?
Optimally something just to install, but I'm not completely afraid of building noobs myself (would take quite some efforts, though).
Thanks!

**Comment by procount** [comment]
Still working on it but the basic version will operate the boot selection dialog so you can choose one of the already installed OSes to boot, but its not complete enough to install them in the first place yet. Is that any good to you?

**Comment by jpfk123** [comment]
Nice :-) , that would actually be what I was looking for, I don't mind getting a mouse or keyboard out when I want to add new stuff but wished to be able to switch os with the remote

**Comment by seppforcher** [comment]
I second that, that is absolutely all I need! Great!

**Comment by procount** [comment]
Look here -> https://sourceforge.net/projects/pinn/files/testing/ and download pinn-211a.zip.
This is a draft version for testing and CEC only works properly for the boot selection dialog.
Treat it the same as noobs-lite.zip. 
I suggest you try it on a new installation.

If you want to try it on an existing installation, make sure you have a backup or clone of your card first.
You could simply replace the noobs files with the pinn files in the first recovery partition to try it.

**Comment by seppforcher** [comment]
I had a chance to try it out.
CEC works for the selection, but when booting (newly installed) Libreelec CEC won't work there anymore.

**Comment by procount** [comment]
I did not have a problem with Librelec, but I noticed on a reboot that CEC would only work on the boot selection dialog after pressing shift to get to the main installation dialog. I think I will have to move the CEC initialisation...

**Comment by procount** [comment]
I found a little time to fix the CEC code for the boot selection dialog in PINN.
Please see -> https://sourceforge.net/projects/pinn/files/testing/ and download pinn-211b.zip.
This is a draft version for testing and CEC only works properly for the boot selection dialog, although you can now select OSes on the selection dialog too (but no buttons except Exit)
Treat it the same as noobs-lite.zip.
This is still a work in progress and may change significantly once released.

**Comment by procount** [comment]
PINN is now fully CEC enabled! 
Please see -> https://sourceforge.net/projects/pinn/files/testing/ and download pinn-211c.zip for the test version. Any feedback welcome before I release it properly
Use the cursor keys and Select key like a mouse.
Use the Channel Up and Down keys to change a list selection.
Key 0 is used as Enter.
Key 9 is used to toggle the advanced menu
Keys 1-8 select the menu buttons
Exit is like Escape.

**Comment by e-tobi** [comment]
I just gave this a try. Is there anything special that needs to be set up in order to make CEC work? Right now the remote does nothing.
Or is there anything I can do to figure out, why it isn't working?

**Comment by procount** [comment]
It should just work. Have you verified your TV uses CEC with any other device?
On my Samsung, when I view the list of sources, it displays PINN next to the HDMI2 port that it is connected to.

**Comment by e-tobi** [comment]
My TV doesn't display the device names.
If I boot an OS from PINN, CEC works - so I guess it's not a TV issue.

You haven't pushed your CEC related changes to GitHub yet, have you?

**Comment by procount** [comment]
No, not yet. Still trying to improve it. It uses the same techniques as Berryboot.

**Comment by procount** [comment]
CEC is now supported in PINN and source code for it is released on github.com/procount/pinn. I haven't backported it into NOOBS yet, but it's there if anyone wants to.

**Comment by danilomalzao** [comment]
procount it is possible to me change the NOOBS to PINN without having to reinstall the OSes ?

**Comment by procount** [comment]
Yes it is, but you need to take particular care over the recovery.cmdline to ensure any 'runinstaller' option will not wipe out your OSes.
I would recommend the following steps:
1. Make a backup of your SD card!
2. copy recovery.cmdline to cmdline.noobs
3. unzip pinn-lite.zip over your noobs partition.
4. Edit recovery.cmdline to remove the 'runinstaller' option
5. Move recovery.cmdline to cmdline.pinn (in case you want to refer to it for installing other OSes in the future)
6. copy cmdline.noobs to recovery.cmdline

You can follow a similar process if you want to go back to NOOBS, taking similar care to delete the runinstaller option.

**Comment by MartinX3** [comment]
I would prefer a solution to use CEC in NOOBS, because NOOBS is official promoted on the Raspberry PI Homepage, in LibreElec and Raspian.

I also would prefer, that the NOOBS and PINN Guys would work together.
Forks are only good, to make enhancements and port them back into the original software, not if they split the community.

**Comment by procount** [comment]
The "noobs partition" is /dev/mmcblk0p1 with the volume name "RECOVERY". It is the partition with the noobs recovery files on it. AIUI the name was deliberately chosen to prevent it auto-mounting.

**Comment by MartinX3** [comment]
@procount thank you very much for your response! :)

I wasn't unsure about it, made a backup of my systems and installed everything from ground off with PINN as SDcard formatter. :)

**Comment by XECDesign** [comment]
> I also would prefer, that the NOOBS and PINN guys work together.
> Forks are only good, if they make enhancements and port them back into the original software, not if they split the community.

We do work together, to some extent. Procount has made many contributions to NOOBS and of course PINN is built on top of NOOBS, so there is some code flowing back and forth. However, PINN and NOOBS have very different goals.

NOOBS installs and boots a small set of operating systems and should be fairly straight forward. PINN is for people who look at NOOBS and think "but I would also like it to do $something_else". That's a rather different target audience, so there's plenty of room for both NOOBS and PINN.

**Comment by MartinX3** [comment]
Thank you for this informative statement. :)
I think it should be placed in the FAQ's of both project, so people could easily understand the differences between them. :D

So "NOOBS" is "PINN Light".
Wouldn't make it sense, if you combine these two projects and allow the people to "opt-in" the PINN-Extensions?
The difference between these two projects are only 8MB and todays microsd cards are quite big.
I got a Samsung 64GB EVO Micro SDXC UHS-I Grade 1 Class 10  Memory Card for 30€.
The size of 8MB wouldn't notice the most people.
Excpecially, if you boot the raspberry pi from an USB HDD or USB stick.
And it would be easier for beginners like me to activate this features instead of possible delete the OS on the way to switch to PINN.
It is time consuming to switch from NOOBS to PINN and I wouldn't notice PINN without my need to activate CEC in the bootloader.
LibreElec, Raspian and the Raspberry PI homepage doesn't tell me on their sites about the existence of PINN, only about NOOBS.

**Comment by XECDesign** [comment]
Closing since there are no plans to add this to NOOBS.

**Comment by MartinX3** [comment]
Okay, better usw PINN instead oft NOOBS.
PINN is also small and has a lot of more opt-in features than NOOBS

**Comment by lmutt** [comment]
May you reconsider adding it to NOOBS? It would be a very useful feature.

**Comment by procount** [comment]
Whilst I can't speak for RPT, I think there is very little chance of that. 
Why don't you just use PINN? It is totally compatible with NOOBS, installs the same OSes, just lots more as well.
Not only does it support CEC, but now you can use your gamepad/joystick as well, with a built in virtual keyboard.
