### ISSUE TITLE
Allow adjustment of the Data Partition size via the NOOBS GUI

### ISSUE THREAD

**Issue by Rob-Bishop** [raspberrypi/noobs#139]

**Comment by Ruffio** [comment]
@Rob-Bishop is this still an issue?

**Comment by NicoHood** [comment]
Any progress in this issue? Or any hint how do change this? At least via a fixed recompilation it would be nice to change the size. It does not need to be via gui directly, but at least for devs to recompile noobs with larger partitions.

**Comment by lurch** [comment]
No need to recompile anything - all you need to do is edit the `partition_size_nominal` value inside `os/Data_Partition/partitions.json`.
Although I've just spotted that the `Data_Partition` folder is missing from NOOBS v1.5.0, so you'll have to copy it from NOOBS v1.4.2 https://downloads.raspberrypi.org/NOOBS/images/NOOBS-2015-09-28/

**Comment by NicoHood** [comment]
Thanks for pointing this out, I will try that.
You should probably place this also somewhere in the readme/wiki.

Inside the GUI you could remove the mb size and open a prompt after the os has been selected to enter the size. However then the size calculation of noobs might be wrong. So i'd then just allow the maximum available space. Or you could edit the json (aka partitionize) in the noobs menu somehow yourself.

**Comment by lurch** [comment]
Please remember that NOOBS is designed for newbie-users, and so is designed to be very simple and very reliable and robust.
IMHO adding a JSON-editor inside NOOBS would be very much the opposite of that!

**Comment by NicoHood** [comment]
No just a simple menu that replaces the filesize that is stored in the json. So we can somehow adjust the data partition inside noobs.

I imagine it like this:
"Oh i have xx bytes left. I think i need another 10gb for the os, but the rest can be used for data. Lets pick 4gb for data". Then the user enters the data partition size (and the default entered value might be 512mb, to just skip the menu and go on). If the user does not want a data partition no menu will promt.

Maybe we could also add a fixed data partition (like now) and just add another entry for a flexible one, where the installation skript somehow asks the user for the size or so. IDK. But having this thing flexible would be great.

Also I am aware that noobs does not intent do resize partitions after they are installed once. But cant i still resize them manually from another linux or will this break the whole boot process (except riscos)?

**Comment by lurch** [comment]
> I imagine it like this:

Yes, but see also my earlier comment https://github.com/raspberrypi/noobs/issues/139#issuecomment-28264938
Feel free to create a prototype and submit a PR ;-)

> But cant i still resize them manually from another linux

As long as you know what you're doing, and the partition numbers remain unchanged, then there should be no problem doing that. See https://github.com/raspberrypi/noobs/issues/296#issuecomment-171286141

**Comment by narspt** [comment]
would it be possible to have a right click context menu (when right clicking data partition entry) to customize partition size? (then showing a simple small window to change the value...)

**Comment by matthuisman** [comment]
I think a simple version of this would be good.

Maybe the menu looks like this:
![mock](https://cloud.githubusercontent.com/assets/6225961/23733836/e3deda36-04df-11e7-9467-042f3535bd0b.png)

It would be completely optional and not shown be default.
- Certain key to open menu
- Only shows partitions that have want_maximized set
- Only allows either setting these to a set size or keeping as maximized

**Comment by matthuisman** [comment]
For anyone else, I have made a proxy script you can use to set sizes in the mean-time.

Here's an example URL
[http://files.matthuisman.nz/noobs.php?url=http://downloads.raspberrypi.org/os_list_v3.json&recalboxOS-rpi3=4000&Lakka_RPi2=3000](http://files.matthuisman.nz/noobs.php?url=http://downloads.raspberrypi.org/os_list_v3.json&recalboxOS-rpi3=4000&Lakka_RPi2=3000)

Set the URL to the os_list file that you want to change the sizes in.
Then use the system name as a GET key with the size as the value.

You would then download NOOBS Lite.
Edit the cmdline.txt file and add

repo="http://files.matthuisman.nz/noobs.php?url=http://downloads.raspberrypi.org/os_list_v3.json&recalboxOS-rpi3=4000&Lakka_RPi2=3000" to the end of it :)

**Comment by matthuisman** [comment]
Hi All,

I have now created a web app that allows partition sizing for NOOBS / PINN.
Works really well and really easy to use (I hope)

Try it out:
http://files.matthuisman.nz/noobs/
