### ISSUE TITLE
Add support for wireless networking

### ISSUE THREAD

**Issue by Rob-Bishop** [raspberrypi/noobs#15]
Currently NOOBS only works with wired networking. Ideally it should also support wireless networking via USB WiFi adaptors.

**Comment by lurch** [comment]
Just to keep things "tied together", PR #243 adds initial support for wireless networking, although I've not tested it myself yet.

**Comment by hansen-m** [comment]
Using NOOBS 1.4.2, I get a pop-up saying that no wireless interfaces are available when clicking on the network button. Is this the same issue? I have an Edimax USB adapter, which has always worked fine in Raspbian. Just wondering if this is a known issue or something I should continue to troubleshoot.

**Comment by maxnet** [comment]
It only supports the official wifi adapter.
http://swag.raspberrypi.org/collections/pi-kits/products/official-raspberry-pi-wifi-dongle

**Comment by lurch** [comment]
...and that support was only added in NOOBS v1.5.x, not NOOBS v1.4.2 ;-)
It also supports http://swag.raspberrypi.org/collections/pi-kits/products/usb-hub-and-wi-fi-adaptor

**Comment by lurch** [comment]
See also #321 - I guess this ticket can be closed now in the light of that.
