### ISSUE TITLE
Make silentinstall power-failure-resistant 

### ISSUE THREAD

**Issue by mherle** [raspberrypi/noobs#154]
If an SD card is setup with noobs for silentinstall, and if during the first boot (when the partitions get resized,created and OS install starts), if for some reason the installation stops (say due to power-failure), then the Pi gets to a bad state requiring human interaction. It'd be better if next boot is able to  

I think, removing the 'runinstaller' keywork from the recovery.cmdlibe file in the  RECOVERY partition AFTER successful OS-install instead of at the beginning should fix it.

Thanks for the awesome work.

**Comment by Ruffio** [comment]
@mherle is this still an issue?

**Comment by mherle** [comment]
Noobs was clearly built for easy install for anybody scenario. We wanted it to work such that we can trigger something from the server end and all the devices would reboot to that stage of the noobs process where it has copied everything to its recovery partition and os-installaion is about to start. All these with zero human involvement on the rPi side.

We ended up doing something differently and now even stopped using it due to changed business strategy.

So, if this Github issue needs to be closed, I don't have any issues with it.

Again, awesome work by NOOBs team.
