### ISSUE TITLE
Unable to use without mouse (tab doesn't work)

### ISSUE THREAD

**Issue by genebean** [raspberrypi/noobs#162]
It currently seems that it is not possible to use NOOBS without a mouse. Selection of items via the keyboard works fine but tabbing does not move you to the options at the top like "Install" nor does it move you to the bottom where you select your language.

**Comment by aliendev** [comment]
Thank you. for whatever reason, it wasn't working for me, until I read the post and tried a second time. Your post was much like the magic of having someone in IT sitting behind you to see an issue happen, and it magically goes away. :)
