### ISSUE TITLE
Text nearly unlegible on TV via HDMI

### ISSUE THREAD

**Issue by genebean** [raspberrypi/noobs#163]
I have my Pi connected to a 47" Insignia TV via HDMI and the text in NOOBS is nearly impossible to read as it is really small and not even remotely clearly displayed. Conversely, once Raspbmc is installed, everything is quite clear in the XBMC interface (I have not yet looked at a console interface). Thanks for looking into this and for making an awesome tool (and hardware product)!

**Comment by lurch** [comment]
Closing due to lack of feedback.
