### ISSUE TITLE
Input codec license codes globally for all distros

### ISSUE THREAD

**Issue by stevekmcc** [raspberrypi/noobs#165]
It would be useful to be able to enter the codec license codes globally, so they are automatically applied to all applicable distros' config.txt with lines like: 
decode_MPG2=0x12345678

A similar request was made by another user in the forum: http://www.raspberrypi.org/phpBB3/viewtopic.php?f=63

**Comment by Ruffio** [comment]
@stevekmcc is this still an issue?

**Comment by stevekmcc** [comment]
I imagine so - I just checked the version comments since back then, and there's no mention of this. As Noobs can't be updated, I don't really have an easy way of finding out.

**Comment by XECDesign** [comment]
I suspect this issue isn't as relevant now. When a license is activated once, it's set in the OTP and doesn't have to be in config.txt for each boot. If this isn't in the existing firmware used in NOOBS, it should be in the next release.
