### ISSUE TITLE
Unable to mount root fs on unknown-block (179,2) 

### ISSUE THREAD

**Issue by tjain90** [raspberrypi/noobs#167]
Hi ,
I have:
Respberry Pi Model B
8 GB micro SD Kingston
NOOBS v1_3_3
Window 7(On Computer)

I tried to install Noobs and it worked smoothly on respberry pi but i am unable to boot any OS it shows: "Unable to mount root fs on unknown-block (179,2) Entering kdb (current=0xcb846c80, pid 1) due to Keyboard Entry ". Please help me in this issue , I need to start my college project and i m feeling helpless.

**Comment by Ruffio** [comment]
@tjain90 @popcornmix is this still an issue?

**Comment by NikolaMandic** [comment]
I just got this error with raspbian it worked just fine now it gave this

**Comment by NikolaMandic** [comment]
but I have not used noobs

**Comment by lurch** [comment]
@NikolaMandic If you're not using NOOBS, then there's not much point adding a comment on the NOOBS bug-tracker ;-)

If you're getting the error using standalone Raspbian, then perhaps your root partition has become corrupt somehow. You could try inserting your SD card into a desktop / laptop Linux PC, and running e2fsck against the faulty root partition?

**Comment by rraghu214** [comment]
Formatting the SD Card with "SD Card Formatter" worked for me. After which copied the image to it using DIsk Imager WIn 32 and then could use it normally.

**Comment by JamesH65** [comment]
This issue is pretty ancient, and seems to be resolved, so closing.

**Comment by VipulKapoor** [comment]
mostly because of not well Formatted or not correct partitions (of sd card), occurs this Panic problem.
can be solved using GParted software. which formats the sd card in a correct manner.
