### ISSUE TITLE
Enhancement idea for custom installations.

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#173]
After the standard boot and root images have been installed to the SD card, copy/untar/decompress a custom tarball for each distro/partition/flavour that exists in the appropriate OS folder to apply user customisations (like wifi setup and other configurations, or scripts that run on startup to do further customisations).

Rationale:

I like to use the latest version of NOOBS whenever it is released, ensuring I get all the latest updates and distro versions.
However, whenever I update to a new version, or reinstall a distro from NOOBS, I end up applying the same customisations and installations over and over again.
I've now learnt to create scripts for these common operations and a custom tarball that I can use to overwrite files like /etc/network/interfaces etc.
But it's still an extra step to perform after NOOBS has finished. So I thought about how this could be applied automatically.

I started by copying my custom tarball to the respective OS installation directory of NOOBS, then trying to use partition_setup.sh to copy this file to the newly installed distro partition.
I couldn't quite get this to work as the copy command complained about not being able to 'stat' the custom tarball, despite my different techniques to find it.
Maybe someone could advise the correct shell scripts I could be use to do this, or the correct location of the tarball (/mnt2/os/Raspbian/custom.tar didn't seem to work for me, nor did mounting /dev/mmcblk0p1 to /tmp/3 - maybe I did something wrong :-( ).

Failing this, an alternative would be for NOOBS to recognise that there is a custom tarball in the os distro directory (maybe 1 for each partition of each flavour..?) and automatically copy/untar it to the respective partition after the default installation, a bit like a simple patch.

I think that this would be an easy NOOB solution to apply a standard customisation to the latest distro releases, without having to create a full custom OS distribution. Especially for simple customisations like setting up the wifi and network connections. 
When a user gets a new NOOB release, or a new distro to install, they just put their standard custom_os_flavour_partition.tar(.xz/.zip/etc) file(s) in the OS directory and let NOOBS install it as normal.

**Comment by Ruffio** [comment]
@procount is this still an issue?

**Comment by procount** [comment]
Why are you asking this on all open issues? Have you read the issue? I have a solution called Noobsconfig which solves the issue and you are free to use it. But it is not included in this Noobs repository. So for Noobs it is still an open issue, and it is up to @lurch as to whether it is included or not. In fact I have now built it into the main recovery program itself rather than making it a script, so this might be a better solution.

**Comment by procount** [comment]
Closing as I don't think this will ever be implemented in NOOBS, and it's in PINN anyway for those that want it.
