### ISSUE TITLE
Setting the Language to English (US) at installation does not work

### ISSUE THREAD

**Issue by gaudetr** [raspberrypi/noobs#179]
I have tried several combinations of 'lang=xx' in the recovery.cmdline file to no avail.  These include 'en', 'us', 'US', 'en_US' and 'en_US.UTF-8'.  I didn't expect much from the last two choices but I figured I'd give them a shot.  At any rate, regardless of the selection, the language is always set to English (UK).  Notwithstanding the argument about which is true English :-), I am wondering what pair of letters would select English (US) as the default language.  FYI, I tried 'de' and sure enough the language is set to Deutsch as expected.

**Comment by Ruffio** [comment]
@gaudetr is this still an issue?

**Comment by procount** [comment]
User reported this bug seems to be related to the silentinstall option too.
[forum post](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=141559&sid=a42e6e0004f94daa17e2db22a76361e7#p977009)

**Comment by XECDesign** [comment]
Please re-open if this is still an issue.
