### ISSUE TITLE
NOOBS with Kali

### ISSUE THREAD

**Issue by sharpdressedcodes** [raspberrypi/noobs#197]
I want to modify NOOBS and add Kali as another os. When I read the github page it says (these instructions assume you're only using a single OS at a time with NOOBS - they won't work if you're running multiple OSes from a single SD card).

I want to run openELEC and Kali from the same SD card. Can you give me any advice as to how I should do it?

I have downloaded the Kali arm image, and when I look inside, it has 0.fat and 1.img. It looks like those are the partitions. I have made a copy of the RISC_OS directory and am starting to modify the files and am stuck on partitions.json.

**Comment by natonatonato** [comment]
sharpdressedcodes, can´t you upload to some cloud service the Kali directory?

I did the tarballs but I got alot of errors, especially in boot.

**Comment by sharpdressedcodes** [comment]
https://drive.google.com/file/d/0Bygh1YAvbYKKZTVkb2hvMm9YTzA/view?usp=sharing

This file will be deleted in a few days.

**Comment by natonatonato** [comment]
Thanks alot!

Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=renatoconstanciofilho@gmail.com&idSignature=22>

Renato


2015-07-08 6:09 GMT-03:00 Greg <notifications@github.com>:

**Comment by SEILERAntonin** [comment]
Hello,
Can you reupload the Kali folder that we have to put to the os folder in NOOBS please ?
I'm interested in too because I want to install Kali Linux and Recalbox with Noobs to my Raspberry Pi.
Thanks a lot in advance for that.

**Comment by lurch** [comment]
@procount Does [PINN](https://github.com/procount/pinn) include Kali now?
(PINN is an enhanced version of NOOBS)

**Comment by procount** [comment]
It includes old versions circa 2016/17 for Pi 1/2/3.
I ran into problems updating to a newer version. See https://forums.kali.org/showthread.php?44787-Partially-SOLVED-Installing-Kali-2019-2a-using-NOOBS-PINN&mode=hybrid

**Comment by SEILERAntonin** [comment]
Yep, PINN includes the 2.1.2 Kali Linux version, but not the new versions (2019, 2020).
I'll try with PINN until you'll arrive to fix the problems you're facing at.
Thanks for your answers.
And good luck.

**Comment by XOD123** [comment]
пожалуйста дайте ссылку на облоко с папкой kali чтобы добавить в папку os

**Comment by lurch** [comment]
@SEILERAntonin You probably want to keep an eye on https://github.com/procount/pinn/issues/266 ? :slightly_smiling_face:
