### ISSUE TITLE
Pressing ESC in OS selection

### ISSUE THREAD

**Issue by NicoHood** [raspberrypi/noobs#200]
Hi!
When i press ESC in the boot selection it always boots the OS at the top (risc os).
It would be cool if you can add a simple reboot here to get back into recovery mode.

**Comment by Ruffio** [comment]
@NicoHood is this still an issue?

**Comment by NicoHood** [comment]
Yes it is still an issue with the current master.

**Comment by NicoHood** [comment]
Oh no it is not actually. Fixed now. Cool =)
