### ISSUE TITLE
Add a custom display mode "5"

### ISSUE THREAD

**Issue by NicoHood** [raspberrypi/noobs#201]
It would be great if you add a custom display mode nr "5" with the users display settings.
For example my display only works with a very special dvi mode and 50hz. Otherwise the screen is just swammi.

Maybe you can realize this as a special rpiconfig global command option, so you can enable overlocking for all os for example. Or you can just let the user choose the hdmi mode, drive, group and similar options. Then you dont need to set every option for every os.

**Comment by NicoHood** [comment]
I'd like to reopen this issue.

I tried noobs again and i could get a sharp display almost working via `tvservice -e "CEA 16 DVI"`. I can patch this myself in the corresponding source files as mode 5 or whatever. But could you please give me a hint how to disable overscan? There is no config.txt, where you'd normally set those settings. Any ideas how to do that?

**Comment by procount** [comment]
Just create your own config.txt file with disable_overscan=1 in it. You can also set your own HDMI_MODE and GROUP settings to suit your TV. I had to do this for my HDMIPI. Then you don't need to patch the source files.

**Comment by NicoHood** [comment]
thx for the note. I was thinking of this, but the file system is read only and has no more space. I guess I have to manually rebuild noobs then with this extra file?

**Comment by procount** [comment]
You don't need to rebuild NOOBS just for the config.txt file!
Just mount /dev/mmdblk0p1 read/write and copy config.txt to it. If that partition is full then you'll have to expand it. Maybe next time you write NOOBS to your card you should also write a dummy file to it of a few MB to reserve some space. Then when you run out of space you can just delete it.

Re: booting from Raspbian - I guess so, but I don't see the point myself. I have enough freedom within NOOBS, but feel free to continue as you wish.

**Comment by NicoHood** [comment]
As mentioned here I cannot mount the partition on my other linux OS:
https://github.com/raspberrypi/noobs/issues/288#issuecomment-180571220

I am just wondering how to boot another OS from raspbian. I mean in which files do i have to look to make this work too under raspbian. Its hard to find information on that. Maybe I can just use it better under raspbian. But I will also try to modify noobs a bit.

**Comment by procount** [comment]
I don't know why you can't mount it. Is it already mounted read-only? In which case try:
`sudo mount -o remount,rw /dev/sdc1 /mnt`
Normally the type can be read automatically, especially if it is FAT

**Comment by NicoHood** [comment]
No I just get `mount: you must specify the filesystem type`.

**Comment by lurch** [comment]
Ahh, maybe you're suffering from #262 then?

If you're trying to understand how the multi-boot feature of NOOBS works, have a look at https://github.com/raspberrypi/noobs/search?q=setRebootPartition&type=Code
