### ISSUE TITLE
Recovery Mode on boot using GPIO pin 3 fails

### ISSUE THREAD

**Issue by cokron** [raspberrypi/noobs#209]
Hey folks, thanks a lot, noobs really rocks!
I have a problem, though: I want to reinstall an OS when the user connects GPIO pin 3 to ground, as specified in the README.md. The user is unable to interact with the system, because the Raspberry PI does not have a computer monitor or keyboard attached. He only gets a (hardware) button that connects GPIO pin 3 to ground.

My recovery.cmdline reads as follows:
quiet vt.cur_default=1 coherent_pool=6M elevator=deadline silentinstall gpiotriggerenable

When I connect GPIO pin 3 and ground and then add power, I see the multi-colored image, immediately followed by: 
sh: can't access tty: job control turned off.

Am I missing something?
Am I counting the pins right:
5V     5V         **ground**
3V    GPIO2   **GPIO3**
I have connected the pins printed in bold (marked with *\* around them).
I have tried this on a Raspberry PI model B+.
I have built noobs based on commit e21b0ea3 and cherry picked 0db975a, which is basically NOOBS v1.3.9.

Is my recovery.cmdline correct?

By the way, is there a documentation for vt.cur_default=1 coherent_pool=6M elevator=deadline?

Thank you very very much,

Björn

**Comment by biswaKL** [comment]
> Even the non-interactive

hod did you got non-interactive reinstallation working... can you please share the steps?

**Comment by procount** [comment]
Non-interactive mode just refers to the silentinstall option that only works on 1st installation. You can read about it in readme.md.

If you want a more advanced non-interactive mode, try PINN which allows multiple os installs during silentinstall and multiple reinstalls if a new version exists (although you should use this option with care).

**Comment by cokron** [comment]
Hello @biswaKL , I modified the sources of noobs and built my own binaries for the SD card.

Have a look into `recovery/mainwindow.cpp`. I changed

```
 if (_allowSilent && !QFile::exists(FAT_PARTITION_OF_IMAGE) && ui->list->count() == 1)
```

into 

```
 if (_allowSilent && ui->list->count() == 1)
```

This way, i can connect pin 5 (= GPIO3) to ground and it will reinstall the system _without any user interaction_. Note that the `silentinstall` option is required as well. I need the fully automatic reinstall, because our users cannot connect a screen or a keyboard to their RPI.

Has everything worked out for you since you asked the question in December, @biswaKL ?

**Comment by biswaKL** [comment]
when i asked, at that time it was working fine,
only problem was, i was using a led to know the status of the os
installation whether its completed or not,  so at that time, even after
completing 100% os was still installing. i need to reboot manually to check
if everything is fine.
Just that part needed to be fixed....
