### ISSUE TITLE
Install a new OS without wiping out data partition

### ISSUE THREAD

**Issue by nickandrew** [raspberrypi/noobs#211]
Data partition should be preserved across reinstalls.

If the data partition is always at the end of the device then there is no reason the partition can't be retained across NOOBS switching to a new OS or reinstalling the current one. I would have thought much of the point of having a separate data partition is that it should be persistent across installs or reinstalls.

**Comment by pickfire** [comment]
There is other boot loader such as https://github.com/maxnet/berryboot which can install new OSes without deleting existing OSes root partition. It can **add OSes** and **delete OSes** option without removing all *OSes*.

**Comment by lurch** [comment]
BerryBoot doesn't use separate partitions like NOOBS does, but SquashFS images; which has it's own benefits and drawbacks. Feel free to use whichever you're happiest with. See also #193

**Comment by nickandrew** [comment]
Docker might provide another alternative to installing different OSes from SD card. Just start a container with the desired OS image, and a persistent user directory.

**Comment by procount** [comment]
PINN v2.8.4 now supports the re-installation of any OS without wiping out the other partitions.
ProjectSpaces allows space to be reserved for future OSes to be installed into.

**Comment by minecraftchest1** [comment]
With what I understand, NOOBS formats the SD card, copying the recovery partition to memory, restoring it after formatting, as well as creating partitions for new SD and storage. The only way I can think of to get what you want would require the data partition(s) to memory as well, slowing down the installation. The best way I can think of to do what you want would require copying the contents of the data partition to external storage and restoring it after installation.

**Comment by XECDesign** [comment]
Closing, since the feature is available in PINN and NOOBS is not under development.
