### ISSUE TITLE
NOOBS installation size idea - modularize!

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#213]
The distros used with NOOBS are getting so large that it is difficult to fit them all onto a 4GB SD card.
NOOBS v1.3.10 has therefore removed all but Raspbian, with the remainder having to be downloaded "on the fly", so it is now closer in function to NOOBS-lite.
Here is an alternative suggestion to harmonise the installation process so that it is suitable for different sizes of SD card or installation preferences.
1. Make NOOBS-lite the primary release of NOOBS. i.e. just the installer with no included OSs. User can unzip this file to a blank FAT32 SD card as now. User could use this as is and download/install any OS from within NOOBS as now.
2. Make each OS to be installed by NOOBS available on the website in a NOOBS installable format. i.e. as .tar.xz files, complete with all the installation slides, .json files etc. and package them up into a zip file for each distro.
3. User can download the zip file(s) for whichever OS distros they want to install and unzip them over the top of their NOOBS-lite installer on the SD card. User could now use this SD card to install those OS to a PI when not connected to a network. If connected to the internet, NOOBS lite could additionally offer the other OS available for download as now.
4. Modify NOOBS to look for OSs on /dev/sda1 in addition to /dev/mmcblk0p1 and the internet. In this way a user can have a minimal NOOBS image on their SD card, with more available space on it for their Distros. They can keep all their OS installation files on a separate USB flash drive, to be plugged in just when they want to re-install. In this way they can still do a recovery option when away from the Internet.

Of course, steps 1-3 could be done by an average user now, but packaging the distros as a zip file and making them available on the website for download would make it easier for newbies to select and download. 
Step 4 needs a modification to NOOBS, but I think it would bring a lot of flexibility without overcomplicating the installation.

**Comment by Ruffio** [comment]
@procount is this still an issue?

**Comment by procount** [comment]
Partially solved by @robbi5, but it would be nice to allow users to download a zip or tar file for each distro so they can choose which to download and integrate into Noobs-lite.

**Comment by procount** [comment]
A similar download feature has been added to PINN.
