### ISSUE TITLE
mainwindow.cpp generates a pop-up window on an A+

### ISSUE THREAD

**Issue by DougieLawson** [raspberrypi/noobs#220]
A fresh download of 1.3.10 on a 8GB microSD card booted on a Raspberry Pi A+ gets the popup as shown on the photo I've dropped on IMGUR.

Selecting "Yes" from that popup appears to run OK and completes the install.

The code that generates the popup is in mainwindow.cpp. I've not looked at what needs to be done to run NOOBS in debug mode for extra docs. Just ask if you need that.
```
tr("Warning: incompatible Operating System(s) detected. The following OSes aren't supported on this revision of Raspberry Pi and may fail to boot or function correctly:") + unsupportedOses,
```

http://i.imgur.com/dZhem1x.jpg

**Comment by lurch** [comment]
Now fixed by NOOBS 1.3.11 (with a new Raspbian image).
