### ISSUE TITLE
Open for Translation?

### ISSUE THREAD

**Issue by angurise** [raspberrypi/noobs#222]
Hi,

Just wondering if it is possible for me to add Chinese translation to the installation process.

I am a Chinese native so I'm pretty sure I can do it well.

Thanks!

**Comment by lurch** [comment]
Yup, please feel free!

**Comment by angurise** [comment]
My bad! Didn't scroll to the bottom and find the instructions.

I'll close this issue for now :)

**Comment by angurise** [comment]
Looks like the Chinese translation has been added to dev branch a year ago
https://github.com/raspberrypi/noobs/blob/dev/recovery/translation_zh_CN.ts
(PR153 https://github.com/raspberrypi/noobs/pull/153)

**Comment by lurch** [comment]
Whoops, looks like that's one of the many patches that was on the dev branch, that never made it across to the master branch.
'master' and 'dev' have now diverged quite a bit (especially with all the changes for NOOBS v1.3.12!) so I'll try to get them back in sync again at some point...

**Comment by angurise** [comment]
Oh okay, so will it make sense if I do a new translation and open a pull request to the master branch?

**Comment by lurch** [comment]
If you want to submit an updated / improved translation than was included in #153 then feel free to submit a new PR, otherwise you don't need to do anything.

**Comment by Ruffio** [comment]
@angurise is this still an issue?

**Comment by angurise** [comment]
Nope, sorry, please close. @Ruffio
