### ISSUE TITLE
one wire support not in noobs 1.3.12 

### ISSUE THREAD

**Issue by msloan75** [raspberrypi/noobs#227]
ds18b20 temperature sensors not showing up in latest release of noobs.

**Comment by lurch** [comment]
NOOBS itself (the OS-installer) has never supported one-wire, and it probably never will.

I *suspect* what you mean is that the version of Raspbian that NOOBS currently installs (2015-01-31) isn't working with your temperature sensors.

Have a look at http://www.raspberrypi.org/documentation/configuration/device-tree.md and https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README and see if that allows you to get it working?
If you're still having problems, ask for help on the [forums](http://www.raspberrypi.org/forums/) (I don't have any one-wire experience myself) and if you **still** can't get it working you'd need to open an issue against the [kernel](https://github.com/raspberrypi/linux/issues).

Closing as invalid, as this isn't a bug in NOOBS itself.
