### ISSUE TITLE
Security flaw: HTTPS not supported on download site

### ISSUE THREAD

**Issue by lukestanley** [raspberrypi/noobs#235]
To reproduce go to:
https://www.raspberrypi.org/downloads
You should see that it doesn't connect.

People on shared wifi often can't verify a download over HTTP and could be easily tricked into downloading malware to their Pi.

**Comment by lurch** [comment]
Well, 'luckily' NOOBS doesn't yet support WiFi ;-)  #15 

Even if it did, I'm not sure how much of a concern this actually is, as even Raspbian (which *does* support wifi) only has HTTP links in its `sources.list` files rather than HTTPS.

So thanks for the report, but closing as invalid.

**Comment by lukestanley** [comment]
Hi lurch, I believe what I said has been misinterpreted and incorrectly closed. The problem is that the place where the image download links are doesn't serve HTTPS. Anyhow, source.list is different, as I believe those files are verified by other means.

**Comment by lurch** [comment]
Ahhh, well the image download links are outside the scope of NOOBS itself, so this still doesn't count as a NOOBS bug. But I'll pass your concern along to the relevant people...

**Comment by lukestanley** [comment]
Great. I did look at the contact page but didn't see a security contact or anything obviously similar.

**Comment by lurch** [comment]
You'll be pleased to hear that the downloads page is now served over an HTTPS (SSL) link https://www.raspberrypi.org/downloads/ and therefore it's now possible to get the NOOBS SHA1 checksums without worrying that they've been interfered with, and thus you can verify that you've got a legitimate NOOBS download :-)

**Comment by bennuttall** [comment]
The downloads page is HTTPS but the image downloads themselves are not, as we only have a certificate for the `www` subdomain.

**Comment by lurch** [comment]
@bennuttall That's fine, I believe the checksums themselves being served over HTTPS (which means you can detect any corruption in the files downloaded over HTTP) is all that's needed.

**Comment by bennuttall** [comment]
Re: above reference in #290 

We now have a wildcard SSL certificate covering the whole raspberrypi,org subdomain namespace.
