### ISSUE TITLE
Data partition: need description

### ISSUE THREAD

**Issue by Tabaluga** [raspberrypi/noobs#248]
Why should I install the data partition? This need to be explained better. Best regards

**Comment by lurch** [comment]
As it already says: "Adds an empty 512MB ext4 format partition to the partition layout."

It's simply an extra empty 512MB partition that you can use for whatever you want. If you don't want it, then don't install it :)
(but as #211 points out, note that the Data Partition also gets wiped when you re-install any OSes - as the warning popup clearly says)
