### ISSUE TITLE
NOOBS download link gives 404 error

### ISSUE THREAD

**Issue by electronicsguy** [raspberrypi/noobs#260]
the download link for Noobs latest gives me 404 error. Only once (out of 20 times) did it succeed:

http://downloads.raspberrypi.org/NOOBS_latest

**Comment by lurch** [comment]
It's always worked fine for me... (including just now)

That link is a redirect to another URL, which it's possible your browser isn't handling properly? Try using a different browser to download the file, and if that doesn't work try this direct link: http://director.downloads.raspberrypi.org/NOOBS/images/NOOBS-2015-02-18/NOOBS_v1_4_0.zip
If it still doesn't work, try downloading NOOBS Lite instead (perhaps your ISP has some kind of restriction on downloading big files?)

**Comment by Ruffio** [comment]
@electronicsguy is this still an issue?

**Comment by lurch** [comment]
Closing due to lack of inactivity. Feel free to add further comments if you're still having problems.

**Comment by electronicsguy** [comment]
No, its working fine now.
