### ISSUE TITLE
After using NOOBS, can't format the sd card 

### ISSUE THREAD

**Issue by tomiesz** [raspberrypi/noobs#270]
I used NOOBS succesfully and later decided to try and install xbian on the sd card. The sd card was in read only mode, despite the lock switch being off.

**Comment by tomiesz** [comment]
it probably was a hardware error on my part (the SD card reader) as i was able to format the card without a problem using my phone. Sorry for the trouble.

**Comment by lurch** [comment]
Glad you managed to resolve your problem so quickly!
If it ever happens again, try using the official SDFormatter tool.
