### ISSUE TITLE
Noobs 1.4 RPi2. OpenElec install

### ISSUE THREAD

**Issue by pbarwich** [raspberrypi/noobs#273]
Either from internet or by copying to /os the install ends up with 775 permissions on /storage and not 755. Also shows owner 1000, not root (0). This prevents /storage/.ssh/authorized_keys being read and thus prevents non-interactive login. There may be other impacts. Installation without noobs using the official openelec image file shows no such problems. Since NOOBS is for noobs like me this took some time to find. Fortunately I had an older version working on a Pi 1B and side by side comparison showed it up.

**Comment by XECDesign** [comment]
Problems with individual distros should be reported upstream
