### ISSUE TITLE
Suggestion: Offical Touch Display support

### ISSUE THREAD

**Issue by Ponsen** [raspberrypi/noobs#283]
Hi!

I just got my new Touch Display and I wanted to suggest the the ability output the screen on said display. Especially when it comes to multi-boot it's a downside not being able to see anything without a HDMI display nearby.

Thank you a lot in advance!

**Comment by freekert** [comment]
I agree! This would be an extremely useful feature, it would eliminate the TV from the entire process.

**Comment by procount** [comment]
See my post (5th post in the thread) here 
https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=120332#p814214.

**Comment by Ponsen** [comment]
Can confirm it working.

**Comment by procount** [comment]
I managed to add touchscreen support to the old NOOBS kernel.
But it appears the RPF have released a new NOOBS with an up to date kernel that uses device tree and includes touchscreen support. Go to the downloads webpage. When will the source be released on github?

**Comment by maxnet** [comment]
>When will the source be released on github?

It is there now.

**Comment by procount** [comment]
Thanks :-)
