### ISSUE TITLE
NOOBS v1.4.2 (offline, Raspbian only) cannot be used with a 4GB SD card

### ISSUE THREAD

**Issue by DeeJay** [raspberrypi/noobs#285]
The first line of INSTRUCTIONS-README.txt says "Insert an SD card that is 4GB or greater in size into your computer."

Since the NOOBS Recovery partition will occupy almost 1GB, and the image file for 2015-09-24-raspbian-jessie.img is itself slightly larger than 4GB, it seems that a 4GB SD card will not be sufficient.

**Comment by lurch** [comment]
I already mentioned this to the Raspbian maintainer, and it's *possible* that future versions of Raspbian will be made slightly smaller, to squeeze in under the 4GB barrier (which will also alleviate the unzipping problems mentioned on https://www.raspberrypi.org/blog/raspbian-jessie-is-here/#comments ).

**Comment by XECDesign** [comment]
INSTRUCTIONS-README.txt has been updated since then
