### ISSUE TITLE
Repository not synced?

### ISSUE THREAD

**Issue by PeterDaveHello** [raspberrypi/noobs#289]
There is v1.4.2 released on 2015-09-24 at the download page:
https://www.raspberrypi.org/downloads/noobs/
![screenshot from 2015-11-11 05 29 22](https://cloud.githubusercontent.com/assets/3691490/11076342/380a8552-8835-11e5-87d9-91e551a3e1e9.png)

But on GitHub there is only v1.4
https://github.com/raspberrypi/noobs/releases
![screenshot from 2015-11-11 05 29 41](https://cloud.githubusercontent.com/assets/3691490/11076344/3b91c6a4-8835-11e5-8e49-1e7d259353fc.png)

Did I miss anything? Or the `.2` is for offline version only? 

Thanks!

**Comment by lurch** [comment]
> Or the .2 is for offline version only?

Exactly - "offline NOOBS" is simply NOOBS v1.4 - the .2 on the end indicates that this includes the third version of Raspbian updated since the release of NOOBS v1.4
Just as I (tried to) explain on the release notes you link to ;-)

**Comment by PeterDaveHello** [comment]
Ok, thanks, just make sure :+1:
