### ISSUE TITLE
Too large icon in os resized too late

### ISSUE THREAD

**Issue by NicoHood** [raspberrypi/noobs#309]
This bug is minor.

If I add an image to the os folder of a distribution that is bigger than 40x40px then it is displayed too big in the rescue menu. After noobs downloaded the online json files the icon is shrinked down correct.

I could not test the boot menu, since it looks like the images are copied somewhere before. (I added the image later).

You may close this as wontfix if you say 40x40px is expected.

**Comment by lurch** [comment]
> You may close this as wontfix if you say 40x40px is expected.

Indeed ;-)
