### ISSUE TITLE
Noobs 1.6

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#310]
So Noobs 1.6 is now available.
Are the only changes related to installing Win10IOT via NOOBS?
I hope the github code here will be updated soon....

**Comment by beta-tester** [comment]
is it normal, that i can not see any commits here of NOOBS 1.5.0, 1.6.0 or 1.7.0 ?
the most recent commit in the raspberrypi/noobs master is from november 2015.
where are the commits of the most recent NOOBS version 1.7.0 ???

**Comment by NicoHood** [comment]
We are all waiting for feedback on that sadly...

**Comment by NicoHood** [comment]
You can close this now I think
