### ISSUE TITLE
NOOBS 1.7 Building

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#314]
Is it me, or does anyone else have trouble downloading the linux kernel for 1.7?

My BUILDME.sh tries to download  "http://sources.buildroot.net/linux-ca312f557513e057c456598528e663fe9d009498.tar.gz"

whereas I thought it was supposed to come from "git://github.com/raspberrypi/linux.git"

EDIT: I downloaded it manually and it's building now. It could be a proxy problem, so I'll try it again later.

**Comment by maxnet** [comment]
It tries to fallback to the sources.buildroot mirror if the original source of any packages it wants to download is unreachable.

**Comment by procount** [comment]
I think it must have been a proxy problem as it downloads happily now.
