### ISSUE TITLE
Raspberry Pi 3 - wrong NOOBS Auto-generated Settings

### ISSUE THREAD

**Issue by matthuisman** [raspberrypi/noobs#319]
Hi,

Using latest NOOBS 1.8 Lite on a Raspberry Pi 3.
After installing some OS's, NOOBs is adding these settings to the config.txt

\# NOOBS Auto-generated Settings:
hdmi_force_hotplug=1
arm_freq=850
core_freq=375

These seem like Raspberry Pi 2 values??

Also, the WiFi in NOOBS doesn't seem to support the RPi3 onboard WiFi - but I'm sure your aware of this.

**Comment by samnazarko** [comment]
This is an OSMC issue.
