### ISSUE TITLE
[Question] Languages

### ISSUE THREAD

**Issue by ppigmans** [raspberrypi/noobs#332]
Hi there! lately i worked on a dutch translation for RC_gui, it was accepted to my amazement, now i wish to translate NOOBS aswell, but i have no idea where to start, can anyone point me in the right direction?

Thanks in advance

**Comment by lurch** [comment]
https://github.com/raspberrypi/noobs/blob/master/README.md#addingupdating-translations

**Comment by maxnet** [comment]
Shouldn't have to add Dutch as new language as it was the first translation ever added to NOOBS...
Can update the lines marked 'unfinished' though

https://github.com/raspberrypi/noobs/blob/master/recovery/translation_nl.ts

**Comment by ppigmans** [comment]
BLEEEEEERGH this pc im working on is slow as heck, ill work on it tonight, see what i can finish and then do the rest in the weekend :) it will be finished Before sunday evening i hope

**Comment by ppigmans** [comment]
the translation is done :)
