### ISSUE TITLE
64 GB Samsung Pro sd card doesnt format - Raspi3

### ISSUE THREAD

**Issue by TheFox1312** [raspberrypi/noobs#340]
Hi!
Noobs doesn't Format my SD Card in the installation process. I selected raspbian and openelec and clicked install. It shows "create new Filesystem (ext4)" but it's do nothing. The green light isn't flashing and after 12 hours he doesn't finished it. My PC shows me a little fat32 Partition, a logical with two fat32 partitions and two unknown partitions.

**Comment by Ruffio** [comment]
@TheFox1312 do you still experience this issue?

**Comment by XECDesign** [comment]
Inactive
