### ISSUE TITLE
(feature request) allow installation from USB

### ISSUE THREAD

**Issue by altsheets** [raspberrypi/noobs#343]
When starting NOOBS, I only see very few options for (Raspian, 2 media centres, Windows, ...) - and all of them need to be downloaded from the internet. We have a very slow internet collection.  

Plus, I would like to install two customized Raspian versions called ROKOS (one for altcoins one for bitcoin) - see [this](https://bitcointalk.org/index.php?topic=1084908.msg15068067#msg15068067) and [this](https://bitcointalk.org/index.php?topic=1084908.msg15081716#msg15081716) post if you want to.

_Feature request:_  
I would much appreciate **NOOBS to be able to use a local data repository, e.g. a USB-stick.** (And I would imagine it is not too difficult to add a button/option "install from local path").

Secondly ... what is the easiest way, to include 2 such "custom images", from within, or into NOOBS? (the images I would use are [here](http://rokos.space/downloads.html)). Is it very complicated? Does it need the image maker (rokos.space) to change much about his image? 

Any hint much appreciated! Thank you very much.

**Comment by procount** [comment]
There are detailed instructions on how to create your own custom inages for noobs in the documentation see README.md at https://github.com/raspberrypi/noobs

If you want to install from USB stick then use PINN which is a fork of noobs that supports that, plus installing from another internet source and other features. See https://github.com/procount/pinn

**Comment by altsheets** [comment]
Wow, thanks a lot. That is great! Many many thanks.

**Comment by Jimmy-Z** [comment]
nice, I'll try that later.

**Comment by procount** [comment]
Now included - close?

**Comment by XECDesign** [comment]
My read of it is that @altsheets wants the os/ directory to be read from USB, but NOOBS and OS itself to be installed to SD (or another USB MSD).

**Comment by procount** [comment]
Yes I agree. And it's done already isn't it - usbaddimages() or something like that?

**Comment by XECDesign** [comment]
Ah, if that's the case, great. If not, it would be a wontfix anyway, so it should be closed either way. Thanks

**Comment by procount** [comment]
mainwindow::addImagesFromUSB()
https://github.com/raspberrypi/noobs/blob/master/recovery/mainwindow.cpp#L1755 
:smile:

**Comment by XECDesign** [comment]
Nice, thanks.

**Comment by altsheets** [comment]
Great, thanks.

I have now told the creator of that ROKOS image:

https://bitcointalk.org/index.php?topic=1084908.msg24326674#msg24326674
