### ISSUE TITLE
Boot error

### ISSUE THREAD

**Issue by mittenchops** [raspberrypi/noobs#347]
After freshly flashing NOOBS_lite_v1_9.zip on a pi3, getting:

`/init: line 27: can't create /sys/class/leds/led0/trigger: nonexistent directory`

**Comment by TomasKostadinov** [comment]
@maxnet Is this already implemented in NOOBS_v2_0_0?
I'm still getting this error, and also my pi randomly crashes during install, while configuring wifi networks, etc, and this is the only error message shown.

**Comment by Traceman** [comment]
Interesting, I just loaded up Pixel. No issues there. However, I did not go w/ Noobs. I went solo. 
I could use some help or advice if anyone can tell me how to get "Motion" to function in Pixel. Its not as it was in Jessie.
