### ISSUE TITLE
Feature request: Boot noobs form an USB stick (USB only environment)

### ISSUE THREAD

**Issue by franzgl** [raspberrypi/noobs#356]
Working with an USB stick only is really nice.

The posts [https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md)
and https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=44177 are great.
Those posts descripe USB only booting.

So booting and working with an USB stick is much more fun.  

It is the only way to boot a USB storage device without an SD card. When the boot is complete you can insert the SD card.  This is nice, because then you can modify the file system or other things that you could not when the root file system is in use.

So here is my feature request:

Please port NOOBS to an USB stick only environment.  USB sticks are more reliable and cheaper than SD cards.  I tried to move NOOBS to the USB stick.  The boot failed because the file **recovery.elf** has hard coded **/dev/mmcblk0**  in it and does not know how to handle **/dev/sda**.  I think also **recovery7.img** has to modified.

I hope you will soon release a new **recovery.elf** file that will work with USB only situations.

I have checked https://github.com/procount/pinn for USB support. But there are only installation images from an USB stick supported, but not booting from USB.

**Comment by lurch** [comment]
The disadvantage of USB booting is that it **only** works with the RPi3, whereas NOOBS has to support *all* models of Raspberry Pi.

**Comment by franzgl** [comment]
When I read the post at https://www.raspberrypi.org/blog/pi-3-booting-part-i-usb-mass-storage-boot/ it looks to me that the Raspbian team will support all models of Raspberry PI plus the PI3 booting from USB.

**Comment by lurch** [comment]
Nope, it's only the bootrom inside the BCM2837 (SoC used on the Pi3) that has support for booting from USB. As the article you linked to explains, earlier models only support "two boot modes: SD boot and USB device boot (used for booting the Compute Module)."

**Comment by ghollingworth** [comment]
It is possible to support MSD on other devices, but you'd still require an SD card with a single file on it (i.e. bootcode.bin)

Otherwise the MSD bootmode will only work on Pi 3.

We've had some experimentation with booting noobs from MSD but are still working on it...

**Comment by procount** [comment]
Well I guess the first question is: **how is it possible to tell *which* device got booted?**
There is no cmdline option for the rootfs in NOOBS and root is mounted on /dev/ram0 in the initramfs.
Even the presence of /dev/mmcblk0p1 doesn't mean it got booted - there might be no bootcode.bin file on it.
So, can vcgencmd provide some info on the booted device? Or must we follow the same bootflow algorithm as the BCM2837 and hope we end up with the same conclusion?

**Comment by lurch** [comment]
...and to further complicate the matter, I believe it's possible to have bootcode.bin on SD, but then boot start.elf and kernel.img off USB, e.g. if using MSD mode on a non-Pi3 device? ;)
(so perhaps you need to know both where bootcode.bin got booted from, and start.elf got booted from?)

**Comment by procount** [comment]
And in that scenario, if you use noobs on USB to select Raspbian on partition 6, will it boot it from mmcblk0p6 or sda6, assuming both are present? I suspect mmcblk0p6 because it is the 1st one it finds......?

Sent from my Samsung device

-------- Original message --------

**Comment by Traceman** [comment]
Okay, I am following somewhat here. I will be involved a whole lot finally. I now have a couple new Raspberry Pi 3/s, Arduino kits, beginner, UNO R3 Project kit, Mega 2560 Project, 2 boxes of 37 sensors and the Smart Robot Car Kit. I have some PIXI cam sets PTZ w/ them. And, one of the LCD scratch pads. And lastly some cams and extra kits (add-ons) for the Raspberry Pi/s. Last and not least one of the Nice Weather Stations. So, I went ahead and added "Arduino for Dummies" as my first book for learning more on the Arduino...and all the Web resources and CD'/s.  So, I  am now sorting and deciding which project I will begin first. I will take each kit and break down into manageable modules so I can teach my ten year old son some electromechanical/Robotic skillsets. And, of course, programming too. I have been working on putting all of this together for quite sometime. Meanwhile, I spent lots of time with my first Raspberry Pi 3. I have lots of variety to work with. So, small simple projects to get my son familiar with things (And for myself too. I do not know all of this.) I have been around this type of thing most of my life and worked at a Process Control Company, Asphalt plants and half a million IT projects all over the Houston/Galveston, Texas areas. So, there you have it. I will learn how this site, not only expects and how we help one another at times, meeting new intelligent people. And lastly, how to maneuver this site while doing my best NOT to do things wrong or add/take/copy or fool around the wrong way here. It is clear to me that you have particular methods as how things are done here. I can take constructive criticism like a man. So, if I do something wrong or disrupt the sites natural flow and rules please let me know and guide me back on track. I will do anything in my power to be an asset to this site and all individuals, companies and other entities that are here. 

Thank you for reading this and its is nice to belong. 
Sincerely, 
Tracy Verlin

**Comment by lurch** [comment]
@Traceman I'm not sure what relevance your comment has to the particular issue being discussed here, but based on what you've written it sounds like you're looking for https://www.raspberrypi.org/forums/

**Comment by Traceman** [comment]
@lurch ;   Actually your topic does have relevance to me. That exact topic matter of fact. However, I apologize for sounding off non-relevant thoughts/feelings/excitement, etc... I did say in there I would not be doing this very thing. So, I'm done. Thank you for the URL to the forums. Have a great week!

**Comment by procount** [comment]
Usb boot is now inplemented - close?

**Comment by XECDesign** [comment]
Thanks
