### ISSUE TITLE
OSMC_pi1 partitions.json parse problem

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#360]
I just tried to install this from the internet, but it bombs out due to a partitions.json parse error.
I can't see any obvious syntax error, but the "uncompressed_tarball_size" for the boot partition is set to **UNC_TS_SIZE_BOOT** which doesn't look right to me.

**Comment by procount** [comment]
INVALID - I just looked directly at the downloads folder on the website and it seems ok. So I don't know where that value came from that was downloaded.....v. strange.

**Comment by lurch** [comment]
Reported it upstream for you :)

**Comment by procount** [comment]
Thanks. I posted it on osmc forum too.
