### ISSUE TITLE
Can you install noobs without imaging  the raspberrypi again?

### ISSUE THREAD

**Issue by LTheGreats** [raspberrypi/noobs#361]
So I was wandering if I would be able to add noobs to the raspberry pi without taking the raspbian I have already installed of of the pi.

**Comment by procount** [comment]
Not directly as you describe, but see https://github.com/raspberrypi/noobs/blob/master/README.md#how-to-create-a-custom-os-version which explains how to turn your existing Raspbian into a custom os that you can then install using NOOBS. The end result is the same but it's a different approach- you'll need to take Raspbian off then put noobs on and add you custom Raspbian back on.

**Comment by XECDesign** [comment]
Answered
