### ISSUE TITLE
Feature Request: Skip Noobs Screen

### ISSUE THREAD

**Issue by cawoodm** [raspberrypi/noobs#368]
This is related to http://raspberrypi.stackexchange.com/questions/59154/
Allow skip of Noobs screen (Shift will get you there anyway) without any delay or prompt.

Also, show that this is, in fact, Noobs somewhere on the screen

**Comment by lurch** [comment]
Duplicate of #168 ?

**Comment by procount** [comment]
Have a look at my response in #168. Not quite as you want yet, but nearly there. Comments?

**Comment by procount** [comment]
Now implemented with no delay or prompt in test version of pinn-212b.zip (see #168)

**Comment by procount** [comment]
Now implemented in released PINN p2.1.2
