### ISSUE TITLE
How to Reset my pi

### ISSUE THREAD

**Issue by max099521** [raspberrypi/noobs#370]
dear all 
I use a raspberry pi2 type b
install from NOOBS_v2_1_0
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"

1.How could I make a reset button backup to default OS (maybe the OS with my code)
2.How could I make my own OS(rebuild my NOOBS?)
3.Is any possibility recover OS not reinstall 
4.I try to use the SCL (PIN5)  and GND (PIN6) , it do not work. 
5.Is any possibility disable noobs install os from network.
......................................................................................
thanks all

**Comment by XECDesign** [comment]
1) I don't understand the question. It's better to ask on the forum, providing much more information.
2) https://github.com/raspberrypi/noobs#how-to-create-a-custom-os-version
3) Unfortunately not. NOOBS is only an installer.
4) Work for what? See 1.
5) Unplug the Ethernet cable.
