### ISSUE TITLE
No Raspbian Lite icon

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#375]
There is a missing line in os_list_v3.json for Raspbian Lite which means that the icon for Raspbian Lite does not get shown in NOOBS.

Please add the following line into the entry for Raspbian Lite:

"icon": "http://downloads.raspberrypi.org/raspbian_lite/Raspbian_Lite.png",

**Comment by lurch** [comment]
That's interesting - last time I looked (which was admittedly ages ago) NOOBS only offered regular Raspbian, and didn't offer Raspbian Lite as an option.

**Comment by XECDesign** [comment]
Thanks, much appreciated. I definitely didn't spend half an hour trying to figure out why the icon wasn't showing up and give up.

**Comment by procount** [comment]
Thanks
