### ISSUE TITLE
Touchscreen tap stopped working?

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#383]
Is it just me, or has the touchscreen tap just stopped working to enter the NOOBS mainwindow (v2.1)?
Once the mainwindow has been entered, the touchscreen works fine, but the initial tap has stopped working for me.

**Comment by procount** [comment]
Ahh, it's just me. BUT it seems necessary to click on the central image. It doesn't wok if you click on the background. Should we add something to the README to that effect?

**Comment by XECDesign** [comment]
I am not sure how many people this would actually affect, but if it happened to you, I suppose there are probably others too. Perhaps a note in README would be okay.
