### ISSUE TITLE
choose wifi wlan0 or wlan1 etc?

### ISSUE THREAD

**Issue by nutpantz** [raspberrypi/noobs#392]
i have never had a issue with my wifi stick being reconized in linux
Realtek Semiconductor Corp. RTL8191SU 802.11n WLAN Adapter

but there was no option to chose which wifi i wanted to use
( the external works much better for me)

is it not support or is there no support to choose?

**Comment by lurch** [comment]
Last time I looked (which was a long time ago - @procount has more up-to-date info) NOOBS only supported the wifi built-in to the Pi3 and the Pi Zero W, and the official RPi Wifi dongle https://www.raspberrypi.org/products/usb-wifi-dongle/

**Comment by XECDesign** [comment]
Correct, the kernel config is kept fairly minimal.
