### ISSUE TITLE
Append some extra "config" at the end of file config.txt in the installation stage

### ISSUE THREAD

**Issue by jccolson** [raspberrypi/noobs#395]
Example
- Create a file config.txt, for activating a specific RTC, in the Noobs's SD card witch contain :
dtoverlay=i2c-rtc,ds1307
- cat this file at the end of the config.txt extracted from boot.tar.xz before rebooting to the newly installed system.

Actually, I have to download Raspbian, patching config.txt in boot.tar.xz and put all stuff onto the directory /os/Raspbian of the SD card.

**Comment by XECDesign** [comment]
NOOBS includes a config.txt editor. There are no plans to add any custom automated patching of config.txt files.

**Comment by procount** [comment]
This sounds like you want to customise the OS (e.g. Raspbian) that is installed by NOOBS, but want to avoid creating a custom os?
Have you looked at my noobsconfig project which hooks into NOOBS to do just what you want?
https://github.com/procount/noobsconfig
