### ISSUE TITLE
Lite v2.3 doesn't check for wifi 

### ISSUE THREAD

**Issue by roryhr** [raspberrypi/noobs#397]
I have a Pi 3B and NOOBS Lite v2.3 but can't install anything. The error message says "Wired network access is required..." and once I click "Ok" the "wifi networks" button is greyed out.

**Comment by XECDesign** [comment]
Does wifi work if you run Raspbian directly?

**Comment by roryhr** [comment]
No. I suspect I have a hardware problem. It'd be nice if there was a test suite I could run to confirm.

**Comment by XECDesign** [comment]
Could you post the output of dmesg and ifconfig?

**Comment by daruvurisai** [comment]
I think There is a problem with hardware can you post the output of the following

**Comment by roryhr** [comment]
Uhh. I guess it's working now? I didn't change anything. 

file:///home/pi/Desktop/ifconfig_dmesg_output.txt

**Comment by roryhr** [comment]
It's working now and I'm not sure I changed anything since I last tried and it failed.

[ifconfig_dmesg_output.txt](https://github.com/raspberrypi/noobs/files/921514/ifconfig_dmesg_output.txt)

**Comment by XECDesign** [comment]
Alright. Since this is not a NOOBS problem. Please post on the forum if you see it again.

**Comment by LickTheCheese** [comment]
i have the same problem, but when i run Raspian directly WiFi works.
