### ISSUE TITLE
NOOBS 2.4 - Italian language update

### ISSUE THREAD

**Issue by bovirus** [raspberrypi/noobs#401]
@lurch 

Hi.

This is my proposal for Italian language update.
Please update it into repository.

Thanks. Best regards.

[NOOBS_2.4.0_translation_it_2017.04.18.zip](https://github.com/raspberrypi/noobs/files/929894/NOOBS_2.4.0_translation_it_2017.04.18.zip)

@softastur
@aldatsa
@cescp
@qsypoq
@qsypoq
@fonic
@sople1
@Akkiesoft
@kadamski
@ResonantWave
@Mangero
@diorray
@s8321414

Could you please update language for NOOBS v. 2.4? Thanks.

Then post here the language or make a pull request for this.

**Comment by XECDesign** [comment]
It would need to be sent as a PR.

**Comment by s8321414** [comment]
Any change from my commit?

**Comment by bovirus** [comment]
@s8321414

Your translation is OK.

**Comment by bovirus** [comment]
@XECDesign 

Pull request created. Please check if it's OK. Thanks.

**Comment by XECDesign** [comment]
Merged, thanks
