### ISSUE TITLE
Q on USB

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#404]
Just a question:

recovery/mainwindow.cpp#1701: `if (devname == "sda"` compared with
recovery/mainwindow.cpp#1725: `if (devname != "mmcblk0"`

Could 1705 be changed to be the same as line 1725 for better generality without introducing an issue?

Well, actually 2 questions, because I'd like to know if in mainwindow.cpp#1736 whether `idt.formatUsbDrive();` executes in a separate thread  or not (since it is not called through the exec() function)?

**Comment by maxnet** [comment]
>Could 1705 be changed to be the same as line 1725 for better generality without introducing an issue?

Then the existing target drive combobox selection would change if first a /dev/sda shows up, and then some seconds later a /dev/sdb shows up that matches the tests.
Doesn't happen when only doing it for /dev/sda, as prior to a sda showing up, the combobox is hidden.

And no, writing the initial partition table to an empty USB drive doesn't execute in separate thread.
But shouldn't take long.

**Comment by procount** [comment]
Thanks!
