### ISSUE TITLE
Recommended image

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#406]
BUG, Minor:
config.h still has RECOMMENDED_IMAGE as "Raspbian" when the image name itself has been changed to "Raspbian with Pixel"

**Comment by XECDesign** [comment]
Thanks. Raspbian should probably just be 'Raspbian', since the description already says it comes with a desktop.

**Comment by procount** [comment]
Yep.

**Comment by procount** [comment]
Done in 2.4.1
