### ISSUE TITLE
Add Screenly OSE image

### ISSUE THREAD

**Issue by vpetersson** [raspberrypi/noobs#415]
Hey guys,

I got a working [Screenly OSE](https://github.com/Screenly/screenly-ose) image for Noobs. Just need to put some final touches on it (add graphics etc). However, I would like to see what the process is for adding that image upstream. How can I contribute this image? I'm happy to put it on a CDN myself.

**Comment by vpetersson** [comment]
After a closer look, it seems like this is all managed in http://downloads.raspberrypi.org/os_list_v3.json

Who's in charge of that?

**Comment by XECDesign** [comment]
Hi Viktor, we're happy to add Screenly to NOOBS. We'll just need the appropriate snippet for os_list_v3.json.

**Comment by vpetersson** [comment]
@XECDesign Excellent. Will post it here this week.

**Comment by vpetersson** [comment]
Here's a draft of the JSON payload. I think that is correct, but it is hard to test it without a MiTM :)

```
        {
            "description": "Screenly Open Source Edition (OSE) - The most popular digital signage platform for the Raspberry Pi",
            "icon": "https://releases.screenlyapp.com/NOOBS/Screenly_OSE.png",
            "marketing_info": "http://releases.screenlyapp.com/NOOBS/marketing.tar",
            "nominal_size": 4002,
            "os_info": "https://releases.screenlyapp.com/NOOBS/os.json",
            "os_name": "Screenly OSE ",
            "partition_setup": "https://releases.screenlyapp.com/NOOBS/partition_setup.sh",
            "partitions_info": "https://releases.screenlyapp.com/NOOBS/partitions.json",
            "release_date": "2016-12-01",
            "supported_models": [
               "Pi Model",
               "Pi 2",
               "Pi Zero",
               "Pi Compute Module",
               "Pi 3"
            ],
            "tarballs": [
                "https://releases.screenlyapp.com/NOOBS/boot.tar.xz",
                "https://releases.screenlyapp.com/NOOBS/root.tar.xz"
            ]
        }
```

Let me know if you need anything from me.

Thanks.

**Comment by procount** [comment]
You can always create your own os_list_v3.json that includes the above contents and put it in the NOOBS recovery partition. NOOBS will load such a file for testing purposes.

**Comment by vpetersson** [comment]
Thanks, @procount. Tested and confirmed working.

**Comment by XECDesign** [comment]
Should be added tomorrow. Thanks.

**Comment by vpetersson** [comment]
👍

**Comment by vpetersson** [comment]
@XECDesign could you ping me here when it's live?

**Comment by XECDesign** [comment]
@vpetersson ping

Should be live now. I'd recommend reducing the description length so that it fits in the window. Just "A digital signage platform" would be good, since the name is already listed and the users just need to know what it is.

**Comment by vpetersson** [comment]
@XECDesign Awesome! Good comment about the description. How many characters can fit?

**Comment by XECDesign** [comment]
Going above 70 seems starts to go over the ethernet icon and then off the box.

**Comment by vpetersson** [comment]
Thanks. Good call.

Let's do this instead:

```
"description": "The most popular digital signage platform for the Raspberry Pi",
 "os_name": "Screenly Open Source Edition (OSE)",
```

**Comment by XECDesign** [comment]
Sounds good. Will update it in a bit. Just checking if usb root, sd boot works. I've noticed usb boot doesn't, so os_list will need a line that specifies that.

**Comment by vpetersson** [comment]
>  I've noticed usb boot doesn't

You mean installing the Screenly onto a USB drive? That should work as far as I know. If not, I will have to take a look.

**Comment by XECDesign** [comment]
NOOBS supports three options
1) Everything on SD
2) Boot on SD and root on USB
3) Everything on USB
1 and 2 will just work in most cases, but 3 requires that partitions_setup takes it into account and that the OS supports either PARTUUID= or LABEL=. When I tried, I just got a black sreen.

**Comment by vpetersson** [comment]
Ah, I see. Ok, let me take a look at that later.

**Comment by XECDesign** [comment]
Heads up that 2 doesn't work either. the kernel boots, but after the plymouth splash, it drops to emergency mode.

**Comment by vpetersson** [comment]
Ok, I will create a new disk image when we release the next version of OSE. It's coming close now as we are at the end of the sprint. Let's stick to 1 for now and then I'll QA 2 and 3.

Thanks for the help.

**Comment by procount** [comment]
> Let's do this instead:
> 
> "description": "The most popular digital signage platform for the Raspberry Pi",
>  "os_name": "Screenly Open Source Edition (OSE)",

@vpetersson : The os_name looks overly long to me. Remember that it is often used as the base name for the OS folder, icon name etc. (by default if not overridden). I would suggest keeping your original "Screenly (OSE)".

**Comment by vpetersson** [comment]
Sure. Let's just call it "Screenly OSE".
