### ISSUE TITLE
Lakka Slides

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#417]
The marketing.tar slides used for Lakka all seem to be related to LibreELEC and not Lakka itself. Seems a bit odd, but probably just an oversight. You might want to mention it to them.
I have a replacement set of slides that I created from material on their website if they want to use them - even if only as an interim measure. They could probably do a better job themselves ;-)

**Comment by XECDesign** [comment]
Thanks for the heads up.

ping @Kivutar

**Comment by Kivutar** [comment]
Fixed, you can close this. Thank you for the report!
