### ISSUE TITLE
NOOBS 2.4, 2.4.1 do not respect locale selection

### ISSUE THREAD

**Issue by lipmane** [raspberrypi/noobs#421]
When I select

English (US) with "us" keyboard

and install Raspbian, I wind up with
LANG=en_GB.UTF-8 , and Shift-3 gives me a British pound symbol instead
of a hash (#).

To reproduce:
1. Boot RPi 3 from NOOBS 2.4.0 or 2.4.1 Offline and network install image on micro SD card.
2. Select Raspbian.
3. Select "English (US)" with "us" keyboard.
4. Install and click "ok" to reboot.
5. When GUI comes up, click on the terminal icon at the upper left to open a terminal.
6. Try Shift-3.  You will get a pound sign.
7. echo $LANG .  You will get en_GB.UTF-8 .

**Comment by XECDesign** [comment]
Thanks for the report. This has been broken since the move from wheezy to jessie. For now, this is a wontfix, but we'll re-visit it later.
