### ISSUE TITLE
less than all space, separate home var partitions

### ISSUE THREAD

**Issue by anomalyst** [raspberrypi/noobs#426]
I would be nice to have room to allocate additional partitions. could there be a free space sub menu to select expansion as: **All, 1/2 [default], 4GB, 2GB, 1GB, None**  of free space.

In the same vein, creation of reasonably sized separate partitions (and corresponding fstab entries) for /home & /var would be nice so when they are out of space the system does not get wonky.

**Comment by procount** [comment]
Have a look at http://www.matthuisman.nz/2017/05/noobs-pinn-set-sizes.html?m=1#disqus_thread for a web based implementation of a lot of your request.

**Comment by XECDesign** [comment]
Sorry, no plans for anything like that.
