### ISSUE TITLE
Feature request : allow wifi to be disabled

### ISSUE THREAD

**Issue by codebrane** [raspberrypi/noobs#435]
I enabled wifi before choosing an install and it always used the version of raspbian on the internet. The connection is too slow to download the entire os and there is no way to get noobs to forget the wifi or turn it off. The only way I could get noobs to install raspbian from the sd card was to turn the router off.

**Comment by procount** [comment]
You could try creating a wpa_supplicant.conf file with no "network=' sections in it and place it on the noobs root partition before booting noobs.

**Comment by codebrane** [comment]
now that's a good idea! thanks for that

**Comment by XECDesign** [comment]
There are no plans to add new features in the near future.
