### ISSUE TITLE
Source for Windows IoT install scripts

### ISSUE THREAD

**Issue by mjmeans** [raspberrypi/noobs#446]
Where is the source for the Windows IoT install scripts for NOOBS? Specifically the files collected from the Windows IoT section of the  API call to http://downloads.raspberrypi.org/os_list_v3.json?

**Comment by procount** [comment]
Windows IoT installation is quite unusual. Most of the installation is done by the post installation script (https://iottools.blob.core.windows.net/win10iotnoobs/partition_setup.sh) after NOOBS has installed the basics. (This file is referenced in the os_list_v3.json file you quoted)

**Comment by mjmeans** [comment]
Yes. I see that. but where is the source for the commands that this scripts references. i.e. the commands in scratch.tar.xz?

**Comment by lurch** [comment]
That's a question for Microsoft, not a question for the developers of NOOBS...
