### ISSUE TITLE
Feature request: Use TV Remote's up/down/enter arrows (CEC) to select OS

### ISSUE THREAD

**Issue by Haris1977** [raspberrypi/noobs#455]
As the title says: Are y planning on implementing this? And i don t mean inside OS's but only in the initial "Select OS to Boot" screen. Berryboot is already equiped with this (but as an app has other problems as well). And i know there is PINN but i am talking about NOOBS here :)

https://imgur.com/a/TUanE

**Comment by XECDesign** [comment]
There are no plans to add any new features to NOOBS in the near future.

**Comment by Haris1977** [comment]
I think this option would rock:) Anyway thanks 4 your feedback!
