### ISSUE TITLE
Thoughts about future updates (in terms of boot menu beautification)

### ISSUE THREAD

**Issue by Haris1977** [raspberrypi/noobs#458]
My thoughts about future updates (boot menu beautification)

1) Black background instead of the ugly white one. This is too bright 4 the eyes :(. Or leave us choose from various pre-installed background images

2) Generally bigger fonts and square in boot menu (fonts are very very small in big screens) and no cursor in boot menu. 99% are using it only to boot into different os's. Cursor can be back on the restore menu (through shift key)

3) Give us the possibility to rename the installed os (eg from openelec_rp1 to OpenELEC Rpi) so as to keep things as "clean" as possible. Just like Berryboot does:)

Hope you can take some of my thoughts into account (especially the 1rst one):) 

Keep up the good work !

**Comment by XECDesign** [comment]
Thanks for the feedback. There are no plans to make any major adjustments to NOOBS in the near future, but the suggestions have been noted.
