### ISSUE TITLE
Add Wifi country selection

### ISSUE THREAD

**Issue by rhuitl** [raspberrypi/noobs#465]
It would be a **very** nice feature for those who live in a region where Wifi channels 12 and 13 are legal (and where they are, they are very popular!) to be able to switch the Wifi country. The UI language and the keyboard layout can already be switched easily.

The PIXEL Raspberry Pi Configuration UI has this feature:
![image](https://user-images.githubusercontent.com/429519/34385002-f614eed0-eb1f-11e7-9ec8-ed7e8c6443e4.png)

Background: it took me quite a while to figure out why my Wifi network is not showing up when installing with NOOBS on my Raspberry Pi Zero W, but I could work around it with the help of #386 and https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=175571. The problem is that many potential NOOBS users will probably have a hard time to recognize what the problem is.

**Comment by XECDesign** [comment]
No plans to add this at this stage.
