### ISSUE TITLE
How to change swap size that comes with noobs

### ISSUE THREAD

**Issue by GustavZ** [raspberrypi/noobs#472]
I installed Raspbian with Noobs on my Raspberry Pi 3 Model B V1.2
It came with 1GB Swap as displayed by `top`
How am i able to change this swapsize?
Is it recommendable to increase it?

**Comment by lurch** [comment]
AFAIK this is purely a Raspbian issue, and nothing to do with NOOBS. A quick google search finds e.g. https://www.raspberrypi.org/forums/viewtopic.php?f=26&t=46472

Whether to increase it or not depends entirely on your use-case, which is obviously something that only you know.
