### ISSUE TITLE
Change pin to force recovery mode

### ISSUE THREAD

**Issue by Thosty** [raspberrypi/noobs#479]
> To force Recovery Mode being entered on boot, connect GPIO pin 3 on header P1 to GND (pin 25)

Pin 3 is currently used for a I2C real time clock in my application. Is it possible to configure which pin should be used for entering recovery mode?

**Comment by lurch** [comment]
I think the only way to do that currently would be to edit https://github.com/raspberrypi/noobs/blob/master/recovery/main.cpp#L132 and then compile your own custom version of NOOBS.

**Comment by Thosty** [comment]
Thank you. I will try that out. Is it normal that the build process runs for more than 6 hours?

**Comment by XECDesign** [comment]
@Thosty please close the issue if that worked for you.

**Comment by Thosty** [comment]
It works :-)
