### ISSUE TITLE
Problems in osmc install script

### ISSUE THREAD

**Issue by ernestomiralles** [raspberrypi/noobs#485]
Hi;

I'm trying install osmc under noobs 2.7.0 and it gives me in install script error, I can't do it. 

Thanks for all.

**Comment by XECDesign** [comment]
I think the problem should be reported here: https://github.com/osmc/osmc/issues

**Comment by ernestomiralles** [comment]
Ok, thanks

**Comment by lurch** [comment]
Issue created at https://github.com/osmc/osmc/issues/436
