### ISSUE TITLE
PINN Firmware issue help

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#492]
After upgrading PINN to the same firmware and kernel as NOOBS 2.8, I'm getting the following errors showing up in messages relating to firmware soc:
```
Jan  1 00:00:03 recovery kern.info kernel: [    2.042270] raspberrypi-firmware soc:firmware: Attached to firmware from 2017-04-05 11:51
Jan  1 00:00:03 recovery kern.info kernel: [    2.044535] clocksource: Switched to clocksource arch_sys_counter
Jan  1 00:00:03 recovery kern.notice kernel: [    2.044887] FS-Cache: Loaded
Jan  1 00:00:03 recovery kern.info kernel: [    2.045127] CacheFiles: Loaded
Jan  1 00:00:03 recovery kern.err kernel: [    2.052296] raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001
```
The last error repeats continuously every 2.5 seconds or so.
I haven't checked if this happens on NOOBS yet (probably not).
Tested on a Pi2.
Am I missing an additional firmware file from the new 4.14 kernel or something?

**Comment by lurch** [comment]
> It's something to do with an incompatibility when using the latest 4.14 kernel with an older firmware

I wonder if it's worth filing an issue at https://github.com/raspberrypi/linux/ ?  Or maybe it's a "known problem" ? \*shrug\*

**Comment by XECDesign** [comment]
Not sure that it helps, but 0x00030046 is get_throttled. Does the issue go away if all your firmware and kernel files match the versions in their stable branch? bootcode.bin might be the first to try.

**Comment by procount** [comment]
Thanks for that info - that indicates I am in the right place.
When I use the same firmware and kernel as NOOBS (4.14.34 + rpi-firmware 5db8e4e) It's ok.
When I downgrade the pinn firmware to 22de0bb (only recovery.elf and bootcode.bin) in order to boot the older OSes, the problem arises. 
But this (22de0bb) firmware works fine with 4.4.50 (so all aligned) and 4.9.80 (not aligned)
I wonder if I need to downgrade some other files as well (dtb files?) or if it's something else?

_(I was just about to raise an issue on the linux repo...)_

It's a shame there's no compatibility matrix between the firmware and the kernel repos.

**Comment by procount** [comment]
@JamesH - Thanks for discussing this.
It looks to me like drivers/firmware/raspberrypi.c!118 is the symptom where it is reported, and the "above code" you refer to os the new rpi_firmware_get_throttled() function !173 or below?  But I think you're saying that this get_throttled call is new in the latest firmware and doesn't exist in the 22de0bb firmware (recovery.elf), hence the problem. 

As @lurch Lurch points out, I'm using this as a sticking plaster until the older OSes get upgraded to use the latest firmware and I can go back to a single firmware. Will this be modified to convert the error to a debug message? Even if not released, could a patch be provided for this? Otherwise I may have to stick with the 4.9.50 kernel until such time as all the older OSes get upgraded.

**Comment by JamesH65** [comment]
@procount Yes, the new code to get the throttled state is only in latest firmware. 

I reckon it should be a debug message, and we will also need to fixup the Linux driver that uses the mailbox call to deal with the state of it not existing , and stop calling it.

**Comment by 6by9** [comment]
Until now there's not been a kernel driver requesting the throttled status via the mailbox before, so it's not really a compatibility thing, just that it's complaining louder than it should.

As James says, it's not the job of the raspberrypi-firmware layer to complain about this, just return the error to the caller to do something sensible on error. In this case it should note the error being "not supported" and stop calling it again. It's a small job, but means interrupting other work to do it. I'd guess one of us will get around to it in the next few working days.

(Conversation ought to shift to https://github.com/raspberrypi/linux/issues/2532 as this isn't a NOOBS issue).
