### ISSUE TITLE
What is the default configuration file used by buildroot?

### ISSUE THREAD

**Issue by talkxin** [raspberrypi/noobs#505]
When I looked at the BUILDME script, I found that it was built directly using the make command. I would like to modify the qemu configuration to debug noobs by referring to the default build configuration. The default configuration file used by make is under "buildroot/configs/" which one? 
Thx
@lurch

**Comment by talkxin** [comment]
***
*** Can't find default configuration ".defconfig"!
***
Makefile:786: recipe for target 'defconfig' failed

**Comment by procount** [comment]
Buildoot/.config?
