### ISSUE TITLE
autoboot.txt overrides boot {part}

### ISSUE THREAD

**Issue by matthuisman** [raspberrypi/noobs#508]
**NOOBs Lite 2.8**
http://director.downloads.raspberrypi.org/NOOBS_lite/images/NOOBS_lite-2018-04-19/NOOBS_lite_v2_8.zip

(Sorry - Not sure of last known working version)

**Current Behaviour**
NOOBS ignores reboot {part} and always boots to boot_partition in autoboot.txt

**Expected Behaviour**
reboot {part} reboots into part and autoboot.txt is ignored.

**Steps to reproduce**

- Format SD card and copy over NOOBs Lite 2.8 files
- Boot NOOBs and install LibreELEC and OSMC 
- Boot LibreELEC, enable SSH
- SSH into LibreELEC (root / libreelec) and do command **reboot 8**
- Observe Pi reboots to OSMC
- SSH into OSMC (osmc / osmc) and do command **sudo reboot 6**
- Observe Pi reboots to LibreELEC

- Put SD card into PC and create autoboot.txt file in root of SD card with below contents
**boot_partition=6**
- Boot Pi
- Observe Pi booting directly into LibreELEC
- SSH into LibreELEC and do command **reboot 8**
- Observe Pi reboots to LibreELEC (and not OSMC as expected)

**Comment by lurch** [comment]
AFAIK this behaviour is all entirely in firmware-land and not in NOOBS-land.
Ping @popcornmix

**Comment by XECDesign** [comment]
I've had a quick go at fixing this:
[bootcode.bin.zip](https://github.com/raspberrypi/noobs/files/2380027/bootcode.bin.zip)

Seems to work for me, but it would be good to get a few testers to check I haven't messed anything else up. It just needs to be extracted onto the NOOBS partition (the one with recovery.elf) as bootcode.bin.

**Comment by matthuisman** [comment]
@thegigibeast
Could you give this a test (above comment)

**Comment by Dustee** [comment]
I just tested, and reboot command works as expected.

My setup is : noobs 2.8, rasplex 1.8 (outdated firmware?), libreelec 8.2.5, retropie latest.

**Comment by XECDesign** [comment]
Thanks for testing, @Dustee. Seems to work well for me too, except for when booting off USB.

Unfortunately, that requires a change to start.elf. We can fix NOOBS and Raspbian relatively quickly (I hope), but then it will take a while for the change to propagate to the other distros.

**Comment by matthuisman** [comment]
@XECDesign

Does they changes break the other distros from booting?
Or, will they simply just continue to have this autoboot issue until they are updated?

**Comment by XECDesign** [comment]
The combination of booting off USB, using autoboot.txt AND a reboot parameter would result in files being loaded from two different partitions. If any of the variables are removed, then everything works.

**Comment by popcornmix** [comment]
Fix should be in latest rpi-update firmware.

**Comment by XECDesign** [comment]
In the process of publishing v2.9 with this fix:
https://github.com/raspberrypi/noobs/releases/tag/v2.9
