### ISSUE TITLE
[os_list_v3.json] Lakka_RPi2 - Please enable for 3B+

### ISSUE THREAD

**Issue by matthuisman** [raspberrypi/noobs#512]
https://downloads.raspberrypi.org/os_list_v3.json
needs Lakka_RPi2 supported_models updated to below to enable Pi3B+ support

```
"supported_models": [
    "Pi 2",
    "Pi 3",
    "Pi Compute Module 3"
],
```
http://mirror.lakka.tv/noobs/Lakka_RPi2/os.json
http://www.lakka.tv/articles/2018/08/12/lakka-211-with-raspberry-pi-3-b-plus-support/

@kivutar @XECDesign

**Comment by kivutar** [comment]
Oh, good catch.

So which one is the Pi3B+ there?

**Comment by XECDesign** [comment]
"Pi 3" should match all pi 3 models, including the B+. I'll update it some time today. Thank you both.

**Comment by matthuisman** [comment]
@kivutar

Your os.json is fine :)
As it already uses "Pi 3".

Just the os_list_v3 needs to be updated on NOOBS side.

Over @ PINN, I had added your beta build, so Pi3B+ users could still use Lakka up-till now.
I will remove that once the os_list_v3 is updated.

**Comment by kivutar** [comment]
I mailed them.

**Comment by XECDesign** [comment]
It should be updated now.

**Comment by matthuisman** [comment]
Thank you!
