### ISSUE TITLE
PARTUUIDs

### ISSUE THREAD

**Issue by procount** [raspberrypi/noobs#514]
I just booted PINN from USB and installed 6 OSes on the USB stick for testing.
The first 2 booted nicely (on partitions 6/7 & 8/9)
The next 3 failed with an unknown PARTUUID (10/11, 12/13, 14/15)
The next 1 booted (16/17), but it booted the rootfs on partition 11 !

Do you see a pattern here? Maybe if you convert those partition numbers to HEX, like the PARTTUUIDs are created, it will become clearer.

So my question is, should the partition number part of the PARTUUID be HEX (like it is created in NOOBS) or DECIMAL?
I haven't tested NOOBS, but I'm using the same code so I expect it will be the same problem. Or has something changed somewhere, because I don't remember this problem occurring before.

**Comment by XECDesign** [comment]
Hex. Are they written as decimal somewhere?

**Comment by procount** [comment]
Everything is HEX: in installed_os.json, cmdline.txt and /etc/fstab of each OS.

Here is what I think is happening:
PINN is initially loading the correct boot partition (10h) from installed_os.json and is reading cmdline.txt OK. But I think it is then interpreting the cmdline "root=PARTUUID=0005bedf-11" as decimal and loading rootfs from partition 11 / 0bh. That then correctly mounts the boot partition from /etc/fstab as PARTUUID=0005bedf-0a =partition 10.

**Comment by procount** [comment]
Ah, the above is not quite right, but I found the bug.

NOOBS is actually booting partition 10 and is rejecting any hex partition numbers because of:
https://github.com/raspberrypi/noobs/blob/master/recovery/bootselectiondialog.cpp#L160 and https://github.com/raspberrypi/noobs/blob/master/recovery/bootselectiondialog.cpp#L166

It works ok for /dev/mmsblk0p10 because it's decimal, but no provision is made for the those last 2 digits being hexadecimal in the case of PARTUUID.

**Comment by procount** [comment]
Ah, Now I remember - it's my mistake, partly. See https://github.com/procount/pinn/issues/150

When storing OSes on USB, NOOBS uses PARTUUIDs to avoid the device changing name. But it still stores the references in os_installed.json as /dev/sdaX. I changed this in PINN to PARTUUIDS for the cases where the USB device _had_ changed device name. But I haven't changed the code in bootselectiondialog to accommodate this change.

So NOOBS won't have this problem, but it will have the original problem. So I guess it's down to me to fix it..... Once done, are you interested in a PR that will fix both issues in NOOBS?

**Comment by procount** [comment]
That's better! Fixed now.

**Comment by XECDesign** [comment]
Yeah, I think a PR for this would be much appreciated.

**Comment by procount** [comment]
Ok, I'll backport it

**Comment by procount** [comment]
I already created PR #497 for the original change a long time ago, so I've just pushed up the bugfix to it.
It built ok, but I'm not able to test at the moment. When I do I'll post the results, unless you have a chance before me :wink:
