### ISSUE TITLE
How to add background.sh

### ISSUE THREAD

**Issue by biswaKL** [raspberrypi/noobs#525]
Can you please elaborate where to add background.sh ?? i tried to add it to pinn via ssh but it says read-only file system. Where can i define  that??
I want to blink a LED until the progress reaches 100%.

**Comment by procount** [comment]
I think it's better if you post this question on my [PINN issue list](https://github.com/procount/pinn/issues), rather than NOOBS, because NOOBS does not support this feature, I will answer over there :wink:
