### ISSUE TITLE
Add Install from URL

### ISSUE THREAD

**Issue by AwesomeIndustry** [raspberrypi/noobs#531]
HI!
I was wondering if you could add some sort of **Install from URL** feature to NOOBS, so it would fetch a disk image from a remote server and install it like normal.

**Comment by XECDesign** [comment]
Sorry, there are no plan to add new features to NOOBS. If you would like a more advanced and more flexible alternative, please take a look at PINN.

https://sourceforge.net/projects/pinn/

**Comment by lurch** [comment]
Also, NOOBS doesn't install "disk images", it can only install an OS from tarballs, and it needs extra meta-data files to tell it what partitions should be created, etc.
