### ISSUE TITLE
os.json file for Screenly OSE 

### ISSUE THREAD

**Issue by prodigy213** [raspberrypi/noobs#547]
Hello,

Can someone who's familiar with Screenly or who's in contact with the maintainer for Screenly OSE please fix the os.json file located at https://releases.screenlyapp.com/NOOBS/os.json? The data inside is pointing to Raspian Lite information instead of Screenly's info. When the install is finished it loads a error message. In order for the install to work I had to revert to an earlier version. The os.json file for that install is below.

https://pastebin.com/h6zXmR7W

Thank you.

**Comment by prodigy213** [comment]
> Hello,
> 
> Can someone who's familiar with Screenly or who's in contact with the maintainer for Screenly OSE please fix the os.json file located at https://releases.screenlyapp.com/NOOBS/os.json? The data inside is pointing to Raspian Lite information instead of Screenly's info. When the install is finished it loads a error message. In order for the install to work I had to revert to an earlier version. The os.json file for that install is below.
> 
> https://pastebin.com/h6zXmR7W
> 
> Thank you.

The message received. Once the installation is finsihed.

Could not expand filesystem, please try raspi-config or rc_gui.
Root partition should be last partition
<OK>

**Comment by XECDesign** [comment]
@vpetersson

**Comment by vpetersson** [comment]
@prescott66 My bad guys. Must have been a merge conflict gone wrong. I've updated the file, but will rebuild the image soon to accommodate for the Pi 4.

**Comment by prodigy213** [comment]
@vpetersson Thanks for updating the os,json file. But Screenly still gives the same message after installation. I will create another ticket.
