### ISSUE TITLE
Raspberrypi 4B cannot load noobs

### ISSUE THREAD

**Issue by zhjgit** [raspberrypi/noobs#553]
I installed the tutorial on the official website and formatted my SD card, because the SD card exceeded 32G. I converted the file system into FAT32, and then decompressed the new version of noobs Lite into my SD card. I tried many times, including rewriting and formatting the full coverage of the card, and could not load noobs.

**Comment by zhjgit** [comment]
Now I want to try using noobs lite image file and burn it to the SD card. I don't know if it's possible, if it's possible, to help create noobs image files.

**Comment by XECDesign** [comment]
For general support, please use the forum.
https://www.raspberrypi.org/forums/index.php

https://www.raspberrypi.org/documentation/installation/noobs.md
https://www.raspberrypi.org/documentation/installation/sdxc_formatting.md

**Comment by zhjgit** [comment]
At the beginning, the green light went on a few times, and then the red light went on all the time. And it's always been this picture.
![微信图片_20190901223607](https://user-images.githubusercontent.com/11417141/64124790-93ef2a00-cdda-11e9-85c9-d44b26724c62.jpg)

**Comment by JamesH65** [comment]
Again, please use the forum for technical support of this sort. Links provided above.

**Comment by procount** [comment]
Did you plug your HDMI cable into the HDMI0 socket - the one next to the USB-C connector?

**Comment by zhjgit** [comment]
@procount I succeeded with the HDMI interface near the power supply. Why? Are there any differences between these two HDMI interfaces?

**Comment by procount** [comment]
Noobs only displays on HDMI0.
