### ISSUE TITLE
enable ssh login in noobs

### ISSUE THREAD

**Issue by Fatflo** [raspberrypi/noobs#556]
What should I configure in menuconfig to enable ssh on noobs OS?
I tried adding openssh/dropbear packages to the build but I still get `ssh: connect to host 192.168.1.161 port 22: Connection refused` when trying to ssh into the os.

**Comment by XECDesign** [comment]
This isn't really the place for general buildroot support. You can check the relevant commits in PINN, but I suspect what you're missing is a line in the init script that would start it.
