### ISSUE TITLE
Rainbow splash image is shown despite disabling in /boot/config.txt

### ISSUE THREAD

**Issue by slrslr** [raspberrypi/noobs#567]
Hello,

i used NOOBS_v3_2_1 on RPi4B and installed full Raspbian 10.
I tried to set disable_splash variable in /boot/config.txt as per the instructions here:
https://www.raspberrypi.org/documentation/configuration/config-txt/boot.md

But it continue to appear.

boot mount points:

$ mount|grep boot

> /dev/mmcblk0p6 on /boot
> /dev/sda6 on /media/pi/boot

Finding all config.txt files in / and grepping splash out of its contents:

$ for file in $(find / -type f -name config.txt 2>/dev/null);do echo $file && grep splash $file;done 

> /boot/config.txt
> disable_splash=1
> /media/pi/boot/config.txt
> disable_splash=1

There some people conclude it does not work: https://raspberrypi.stackexchange.com/questions/22047/disabling-rainbow-splash-screen-does-not-work
Can you fix this or remove that from Raspberrypi.org documentation?

**Comment by procount** [comment]
You are probably seeing the splash screen from noobs.
Create a config.txt file on your noobs recovery partition (/dev/mmcblk0p1) and add disable_splash=1 there.

**Comment by slrslr** [comment]
that worked,
mkdir /media/recovery;mount /dev/mmcblk0p1 /media/recovery
cp /boot/config.txt /media/recovery/
(/boot/config.txt already contain disable_splash=1 line)
reboot

But it gives me an impression that it did not save any boot time as i thought. The splash lasts maybe 12 seconds and without it there is black screen and boot time is roughly same.

**Comment by procount** [comment]
Correct.
It takes virtually no time to display the rainbow test screen. The Pi is not just sat there doing nothing whilst the splash screen is showing, it is still initialising.

**Comment by lurch** [comment]
Yup, IIRC the rainbow splash is displayed by the GPU when `start.elf` is loaded, and ISTR reading somewhere that it's actually only 4 pixels which are blended and scaled to fill the whole screen.

I don't _think_ I've ever seen the rainbow splash being displayed for a whole 12 seconds though :confused:  Is your SD card particularly slow?
