### ISSUE TITLE
Add Endless OS installation support

### ISSUE THREAD

**Issue by AsciiWolf** [raspberrypi/noobs#587]
[Endless OS](https://endlessos.com) added official Raspberry Pi support in their latest stable release. Please, consider adding Endless OS to the list of OSes supported by NOOBS. It is a mature operating system targeted at regular users.

**Comment by XECDesign** [comment]
NOOBS support is normally offered by upstream devs, we just include a relevant snippet in our json file.

**Comment by lurch** [comment]
I believe @procount is more supportive of actively adding 3rd-party OSes to his [PINN](https://github.com/procount/pinn/) project (a spin-off of NOOBS).

**Comment by AsciiWolf** [comment]
I have reported it to the PINN project instead. Thanks!
