### ISSUE TITLE
hdmi_boost config parameter

### ISSUE THREAD

**Issue by adammw** [raspberrypi/noobs#60]
My Raspberry Pi always generates graphics corruption unless config_hdmi_boost is set up high. Can the default config.txt set config_hdmi_boost to 7 (is it safe to do so) or will this cause some issues for people who's screen works fine by default?

**Comment by fredericofs** [comment]
I have the same question:
Can i
Always use hdmi_boost=7 without burning the pi?

**Comment by lwrbakro** [comment]
@Rob-Bishop Could you tell me more about the followings: 
 - What does the `hdmi_boost` option change?
 - What does each level represent?

Can anyone tell me where to look, to find more about this option and its operation mechanism?

Thanks :)

**Comment by lurch** [comment]
> Can anyone tell me where to look, to find more about this option and its operation mechanism?

https://www.raspberrypi.org/documentation/configuration/config-txt.md
