### ISSUE TITLE
noobs stuck in rainbow screen on new raspberry pi 400

### ISSUE THREAD

**Issue by Bassinator** [raspberrypi/noobs#605]
I formatted several SD Cards with sd card formatter under linux and installed noobs. They all boot and install the os on my Raspi 4 but stuck on rainbow screen with my new raspberry pi 400.

**Comment by procount** [comment]
Have you tried plugging your monitor into the other HDMI port?

**Comment by Bassinator** [comment]
You are right. Its not the port beside the USB-C Power port, but beside the SD-Card Slot. Sorry

**Comment by Bassinator** [comment]
And Thanks for helping.
