### ISSUE TITLE
Recovery Wallpaper

### ISSUE THREAD

**Issue by duckida** [raspberrypi/noobs#608]
Hi. I checked the wallpaper([/recovery/wallpaper/png](https://github.com/duckida/noobs/blob/master/recovery/wallpaper.png)) and noticed it was **from 2013!!!**. I have created a more modern one:
![New Wallpaper](https://raw.githubusercontent.com/duckida/TestWallpp/main/Screen%20Shot%202020-11-16%20at%2012.58.27%20PM.png)

Can we please use this new one? It will be the first step in making NOOBS consistent with Raspberry Pi OS!

**Comment by duckida** [comment]
@lurch Please See

**Comment by duckida** [comment]
Feel free to make your own recovery wallpapers and submit them

**Comment by lurch** [comment]
@duckida It's @XECDesign 's decision to make, not mine :wink:

**Comment by XECDesign** [comment]
These kinds of changes would need to go through the (very busy) design team. We are currently only making basic maintenance changes to NOOBS to keep it working with newer models, so I don't think the wallpaper is really an issue that's likely to get looked at.

**Comment by duckida** [comment]
@XECDesign Please See #610
