### ISSUE TITLE
Update Screenshots

### ISSUE THREAD

**Issue by duckida** [raspberrypi/noobs#611]
Hi. As part of #610, we need to change the screenshots which depict the 7-year-old Raspbian. We must take new screenshots of Raspberry Pi OS Buster and its new UI.

**Comment by lurch** [comment]
The "good news" is that these screenshots are in http://downloads.raspberrypi.org/raspios_armhf/marketing.tar which means they're not built into NOOBS and are therefore much easier to update (**if** anyone has the time to do so).
