### ISSUE TITLE
Noobs download

### ISSUE THREAD

**Issue by Jayson380** [raspberrypi/noobs#615]
what causes "unable to expand NOOBS v3_5_0.zip

**Comment by procount** [comment]
If you are just using standard Windows file manager to expand it, try installing 7zip and use that instead.

**Comment by Jayson380** [comment]
Im using Macbook 13"


> If you are just using standard Windows file manager to expand it, try installing 7zip and use that instead.

Im using Macbook.

**Comment by lurch** [comment]
https://www.raspberrypi.org/documentation/installation/installing-images/README.md suggests some alternative "unzip" programs.

@XECDesign Does NOOBS now use ZIP64 as well?

**Comment by procount** [comment]
That page omits the fact that Raspberry Pi Imaging Utility can also be used to write NOOBS zip files.

**Comment by lurch** [comment]
Feel like submitting a docs PR @procount ? :wink:

**Comment by procount** [comment]
I'll see if I can fit it in :wink:

**Comment by XECDesign** [comment]
> @XECDesign Does NOOBS now use ZIP64 as well?

Not sure off the top of my head, but the full archive probably does. Can investigate further if The Unarchiver doesn't work and the checksum has been verified.
