### ISSUE TITLE
Add SSD support

### ISSUE THREAD

**Issue by coldspark29** [raspberrypi/noobs#629]
I would like to use NOOBS with an SSD, but the last time I checked it didn't work. Unfortunately BerryBoot also doesn't work for most images with the Pi4 yet.

**Comment by lurch** [comment]
AFAIK the Pi just sees an SSD as a "generic USB drive", and I think NOOBS _does_ have support for USB drives?
If not, I'm fairly sure that PINN does. https://github.com/procount/pinn (ping @procount )

**Comment by procount** [comment]
PINN and NOOBS should work equally well with SSD.
