### ISSUE TITLE
sudo apt update hash issues with Raspberry pi 4 8GB RAM

### ISSUE THREAD

**Issue by mrusli70** [raspberrypi/noobs#632]
Hi

Currently i am having these issues which i did not encounter since yesterday. When i do sudo apt update on the terminal. How do I resolve these problems. 

pi@raspberrypi:~ $ sudo apt update
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Get:2 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:3 http://103.1.138.206/archive.raspberrypi.org/debian buster/main armhf Packages [378 kB]
Err:3 http://103.1.138.206/archive.raspberrypi.org/debian buster/main armhf Packages
  File has unexpected size (377634 != 377640). Mirror sync in progress? [IP: 103.1.138.206 80]
  Hashes of expected file:
   - Filesize:377640 [weak]
   - SHA256:fd9e88af2432f1f241f85c031be6e3c28ff6b33ef8854582ab754071c884a389
   - SHA1:a37690cdc171e2ea26e7a19784338e9899e0997d [weak]
   - MD5Sum:efccf610ef176a9864f04edad5cd4e2d [weak]
  Release file created at: Wed, 11 Aug 2021 07:30:54 +0000
Fetched 32.6 kB in 1s (28.1 kB/s)
Reading package lists... Done
E: Failed to fetch http://103.1.138.206/archive.raspberrypi.org/debian/dists/buster/main/binary-armhf/Packages.gz  File has unexpected size (377634 != 377640). Mirror sync in progress? [IP: 103.1.138.206 80]
   Hashes of expected file:
    - Filesize:377640 [weak]
    - SHA256:fd9e88af2432f1f241f85c031be6e3c28ff6b33ef8854582ab754071c884a389
    - SHA1:a37690cdc171e2ea26e7a19784338e9899e0997d [weak]
    - MD5Sum:efccf610ef176a9864f04edad5cd4e2d [weak]
   Release file created at: Wed, 11 Aug 2021 07:30:54 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
pi@raspberrypi:~ $

**Comment by XECDesign** [comment]
This is not a NOOBS issue. You seem to have something in /etc/apt/sources.list or /etc/apt/sources.list.d/ that points to a bad mirror.

For further help, please try the forum.
