### ISSUE TITLE
Quickly reboot between installed OSs

### ISSUE THREAD

**Issue by 9p6** [raspberrypi/noobs#635]
I'm not sure how exactly the boot process works on Pi and whether the OSes are even aware of being started from NOOBS but if they do it would be very convenient to be able to switch between them from their own reboot menu (*Reboot into X*). I think `autoboot.txt` functionality might be useful here for a quick hack

https://github.com/raspberrypi/noobs#how-to-bypass-the-recovery-splashscreen-and-boot-directly-into-a-fixed-partition

This would allow to seamlessly reboot into other system without the need to connect keyboard to press Shift (or using GPIO button). Has anyone tried implementing something resembling that?

**Comment by XECDesign** [comment]
You should be able to just run `reboot $part_num` already, no need for autoboot.txt.

**Comment by lurch** [comment]
I agree that this would definitely need to be a 3rd-party project, but @9p6 you may find [this article](https://github.com/raspberrypi/noobs/wiki/NOOBS-partitioning-explained) to be a useful starting point (although might be out of date!).

**Comment by procount** [comment]
I wrote some scripts to parse the noobs json file so that the OS can be selected by hardware dip switches. This could form the basis of such a gui tool. It was written up by another user on the forum. Come back if you can't find it.

**Comment by procount** [comment]
Yes, only USB, not Bluetooth. TV remote control depends on your brand of TV, but works with most. 
For both you may have to configure the key mappings  but it is fairly straightforward.
