### ISSUE TITLE
can't download lakka for rpi4

### ISSUE THREAD

**Issue by Therealsidthecat** [raspberrypi/noobs#642]
`when` i try to install lakka I get multiple "can't download file" errors
![IMG_20211227_032603](https://user-images.githubusercontent.com/90522752/147457558-8adf9dd0-6f86-4246-8e17-702779a950e4.jpg)
![IMG_20211227_032545](https://user-images.githubusercontent.com/90522752/147457562-af24ac64-9f5c-415e-b21d-3593c75bd653.jpg)

**Comment by XECDesign** [comment]
Fixed in https://github.com/raspberrypi/noobs/commit/6df566a76b9b893e4521313e9e0d531a99cbaba5

Should be in the  next release of NOOBS, which will be in the new year.

**Comment by lurch** [comment]
:point_up: ping @procount who I know was also having problems with SSL certificates.

**Comment by procount** [comment]
I thought this was fixed.
Was a certificate missed?

**Comment by lurch** [comment]
@procount Hmm, perhaps I'm getting my issues muddled up, in which case I apologise; but I thought this was the Let'sEncrypt thing where you had to turn off all SSL security in order to avoid the warning dialogs? :man_shrugging:

**Comment by procount** [comment]
Already fixed in PINN, but maybe NOOBS is a bit behind....
