### ISSUE TITLE
How does recovery.elf specify to the kernel to load recovery.rfs?

### ISSUE THREAD

**Issue by furrysalamander** [raspberrypi/noobs#643]
I've been trying to find the place where recovery.rfs is specified as the initramfs, and I can't find details anywhere.  I know that it happens, but if I try to create my own buildroot configuration from scratch, I can't find the right information to specify that it should load recovery.rfs as /dev/ram0.  

https://github.com/raspberrypi/noobs/wiki/NOOBS-partitioning-explained#noobs-bootup-low-level

Can someone explain what I'm missing here?  I can't find references to the file anywhere.

**Comment by lurch** [comment]
IIRC if `start.elf` (or `start4.elf`) isn't found, but `recovery.elf` **is** found (`recovery.elf` is just a [renamed](https://github.com/raspberrypi/noobs/blob/master/BUILDME.sh#L177) `start.elf`), then that automatically switches the bootloader into "recovery mode"; and in "recovery mode" it automatically loads `recovery.rfs` as an initramfs (as detailed in the wiki page you've linked to).

Alternatively, you could continue to use `start.elf` and specify the initramfs in `config.txt` https://www.raspberrypi.com/documentation/computers/config_txt.html#initramfs  (which is probably a better option, given that NOOBS is deprecated).
